# Netlify configuration file for building and deploying the Cursorless website.
# Read by Netlify GitHub app.

[build]
  command = "./scripts/build-and-assemble-website.sh"
  publish = "dist/cursorless-org"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
