export type ActionType =
  // | "callAsFunction"
  | "clearAndSetSelection"
  // | "copyToClipboard"
  // | "cutToClipboard"
  // | "deselect"
  // | "editNewLineAfter"
  // | "editNewLineBefore"
  // | "executeCommand"
  // | "extractVariable"
  // | "findInWorkspace"
  // | "foldRegion"
  // | "followLink"
  | "getText"
  | "highlight"
  // | "indentLine"
  // | "insertCopyAfter"
  // | "insertCopyBefore"
  // | "insertEmptyLineAfter"
  // | "insertEmptyLineBefore"
  // | "insertEmptyLinesAround"
  // | "moveToTarget"
  // | "outdentLine"
  // | "pasteFromClipboard"
  | "remove"
  // | "replace"
  // | "replaceWithTarget"
  // | "reverseTargets"
  // | "rewrapWithPairedDelimiter"
  // | "scrollToBottom"
  // | "scrollToCenter"
  // | "scrollToTop"
  | "setSelection"
  | "setSelectionAfter"
  | "setSelectionBefore";
