;; Generated by the following command:
;; `curl https://raw.githubusercontent.com/tree-sitter/tree-sitter-go/master/src/node-types.json | jq '[.[] | select(.type == "_statement" or .type == "_simple_statement") | .subtypes[].type]'`
[
  (assignment_statement)
  (dec_statement)
  (inc_statement)
  (send_statement)
  (short_var_declaration)
  (break_statement)
  (const_declaration)
  (continue_statement)
  (defer_statement)
  (empty_statement)
  (expression_switch_statement)
  (fallthrough_statement)
  (for_statement)
  (go_statement)
  (goto_statement)
  (if_statement)
  (labeled_statement)
  (return_statement)
  (select_statement)
  (type_declaration)
  (type_switch_statement)
  (var_declaration)
] @statement

(composite_literal
  type: [
    (map_type)
    (struct_type)
  ]
) @map

(composite_literal
  type: [
    (implicit_length_array_type)
    (array_type)
    (slice_type)
  ]
) @list

[
  (interpreted_string_literal)
  (raw_string_literal)
] @string @textFragment

(comment) @comment @textFragment
