;; https://github.com/tree-sitter/tree-sitter-php/blob/master/php/src/grammar.json

;; @statement generated by the following command:
;;  curl https://raw.githubusercontent.com/tree-sitter/tree-sitter-php/master/src/node-types.json | jq '[.[] | select(.type == "_statement" or .type == "_simple_statement") | .subtypes[].type]' | grep -v '\"_' | sed -n '1d;p' | sed '$d' | sort
;; and then cleaned up.
[
  (break_statement)
  (class_declaration)
  (const_declaration)
  (continue_statement)
  (declare_statement)
  (do_statement)
  (echo_statement)
  (empty_statement)
  (enum_declaration)
  (expression_statement)
  (for_statement)
  (foreach_statement)
  (function_definition)
  (function_static_declaration)
  (global_declaration)
  (goto_statement)
  (interface_declaration)
  (named_label_statement)
  (namespace_definition)
  (namespace_use_declaration)
  (return_statement)
  (switch_statement)
  (trait_declaration)
  (try_statement)
  (unset_statement)
  (while_statement)
  (method_declaration)

  ;; Disabled on purpose. We don't consider these to be statements.
  ;; (compound_statement)

  ;; Disabled on purpose. We have a better definition of these below.
  ;; (if_statement)
] @statement

(
  (program) @class.iteration @statement.iteration @namedFunction.iteration
  (#document-range! @class.iteration @statement.iteration @namedFunction.iteration)
)

(
  (program) @name.iteration @value.iteration @type.iteration
  (#document-range! @name.iteration @value.iteration @type.iteration)
)

;;!! { }
;;!   ^
(_
  .
  "{" @interior.start.endOf
  "}" @interior.end.startOf
  .
)

;;!! { }
;;!   ^
(compound_statement
  "{" @name.iteration.start.endOf @value.iteration.start.endOf @statement.iteration.start.endOf
  "}" @name.iteration.end.startOf @value.iteration.end.startOf @statement.iteration.end.startOf
)

[
  (shell_command_expression)
  (string)
  (encapsed_string)
] @string

(string
  .
  "'" @textFragment.start.endOf
  "'" @textFragment.end.startOf
  .
)

(encapsed_string
  .
  "\"" @textFragment.start.endOf
  "\"" @textFragment.end.startOf
  .
)

(shell_command_expression
  .
  "`" @textFragment.start.endOf
  "`" @textFragment.end.startOf
  .
)

(comment) @comment @textFragment

;;!! if (true) {} else {}
(
  (if_statement) @ifStatement @statement @branch.iteration
  (#not-parent-type? @ifStatement else_clause)
)

;;!! if (true) {} else {}
;;!      ^^^^
(
  (if_statement
    "if" @branch.start @branch.removal.start
    condition: (_
      (_) @condition
    )
    body: (_) @branch.end @branch.removal.end
    alternative: (else_clause
      "else" @branch.removal.end.startOf
      (if_statement)? @branch.removal.end.startOf
    )?
  ) @condition.domain
  (#not-parent-type? @condition.domain else_clause)
)

;;!! else if (true) {}
;;!           ^^^^
(else_clause
  "else" @condition.domain.start @branch.start
  (if_statement
    condition: (_
      (_) @condition
    )
    body: (_) @condition.domain.end @branch.end
  )
)

;;!! else {}
(else_clause
  body: (compound_statement)
) @branch

;;!! [aaa, bbb]
(array_creation_expression) @list

;;!! ["aaa" => 0, "bbb" => 1];
(array_creation_expression
  "[" @collectionKey.iteration.start.endOf @value.iteration.start.endOf
  (array_element_initializer
    "=>"
  )
  "]" @collectionKey.iteration.end.startOf @value.iteration.end.startOf
) @map

;;!! ['num' => 1];
;;!   ^^^^^
;;!            ^
(array_element_initializer
  (_) @collectionKey @value.leading.endOf
  "=>"
  (_) @value @collectionKey.trailing.startOf
) @_.domain

;;!! class Foo {}
(class_declaration
  name: (_) @name
  body: (_
    "{" @namedFunction.iteration.start.endOf
    "}" @namedFunction.iteration.end.startOf
  )
) @class @type @name.domain

;;!! class Foo { }
;;!! interface Foo { }
(declaration_list
  "{" @statement.iteration.start.endOf
  "}" @statement.iteration.end.startOf
)
(declaration_list
  "{" @name.iteration.start.endOf @value.iteration.start.endOf @type.iteration.start.endOf
  "}" @name.iteration.end.startOf @value.iteration.end.startOf @type.iteration.end.startOf
)

;;!! interface Foo {}
(interface_declaration
  name: (_) @name
) @type @name.domain

;;!! enum Foo {}
(enum_declaration
  name: (_) @name
  body: (_
    "{" @name.iteration.start.endOf @value.iteration.start.endOf @type.iteration.start.endOf
    "}" @name.iteration.end.startOf @value.iteration.end.startOf @type.iteration.end.startOf
  )
) @type @name.domain

;;!! function foo() {}
[
  (function_definition
    name: (_) @name
    parameters: (_)? @type.leading.endOf
    return_type: (_)? @type
  )
  (method_declaration
    name: (_) @name
    parameters: (_)? @type.leading.endOf
    return_type: (_)? @type
  )
] @namedFunction @_.domain

(expression_statement
  (assignment_expression
    right: [
      (anonymous_function)
      (arrow_function)
    ]
  ) @namedFunction.start
  .
  ";"? @namedFunction.end
)

;;!! function(): int {}
;;!  ^^^^^^^^^^^^^^^^^^
;;!              ^^^
(anonymous_function
  parameters: (_) @type.leading.endOf
  return_type: (_)? @type
) @anonymousFunction @type.domain

;;!! fn(): int => 0;
;;!  ^^^^^^^^^^^^^^
;;!        ^^^
;;!          ^
(arrow_function
  parameters: (_) @type.leading.endOf
  return_type: (_)? @type
  body: (_) @value
) @anonymousFunction @_.domain

;;!! foo()
(function_call_expression
  function: (_) @functionCallee
) @functionCall @functionCallee.domain

;;!! foo()->bar()
(member_call_expression
  object: (_) @functionCallee.start
  name: (_) @functionCallee.end
) @functionCall @functionCallee.domain

;;!! foo()?->bar()
(nullsafe_member_call_expression
  object: (_) @functionCallee.start
  name: (_) @functionCallee.end
) @functionCall @functionCallee.domain

;;!! new Foo()
(object_creation_expression
  "new" @functionCallee.start
  .
  (_) @functionCallee.end
) @functionCall @functionCallee.domain

;;!! namespace Foo\Bar;
;;!            ^^^^^^^
(namespace_definition
  name: (_) @name
) @name.domain

;;!! foreach ($values as $v) {}
;;!           ^^^^^^^
;;!                      ^^
(foreach_statement
  (_) @value
  .
  "as"
  .
  (_) @name
) @_.domain

;;!! throw $foo;
;;!        ^^^^
(throw_expression
  (_) @value
) @value.domain

;;!! switch ($foo) { }
;;!         ^^^^^
;;!                 ^
(switch_statement
  condition: (_
    (_) @value
  )
  body: (_
    "{" @branch.iteration.start.endOf @condition.iteration.start.endOf
    "}" @branch.iteration.end.startOf @condition.iteration.end.startOf
  )
) @value.domain

;;!! case 0: break;
;;!       ^
(case_statement
  value: (_) @condition
) @condition.domain

;;!! case 0: break;
;;!         ^
(case_statement
  ":" @interior.start.endOf
  (_) @interior.end.endOf @_dummy
  (_)? @interior.end.endOf
  .
  (#not-type? @_dummy compound_statement)
)

;;!! default: break;
;;!          ^
(default_statement
  ":" @interior.start.endOf
  (_) @interior.end.endOf @_dummy
  (_)? @interior.end.endOf
  .
  (#not-type? @_dummy compound_statement)
)

[
  (case_statement)
  (default_statement)
] @branch

;;!! do {} while (true);
;;!               ^^^^
(do_statement
  condition: (_
    (_) @condition
  )
) @condition.domain

;;!! while (true) {}
;;!         ^^^^
(while_statement
  condition: (_
    (_) @condition
  )
) @condition.domain

;;!! for ($i = 0; $i < $size; $i++) {}
;;!               ^^^^^^^^^^
(for_statement
  condition: (_) @condition
) @condition.domain

;;!! true ? 0 : 1
;;!  ^^^^
;;!         ^   ^
(conditional_expression
  condition: (_) @condition
  body: (_) @branch
) @condition.domain @branch.iteration

(conditional_expression
  alternative: (_) @branch
)

;;!! try {} catch () {} finally {}
(try_statement
  "try" @branch.start
  body: (_) @branch.end
) @branch.iteration

[
  (catch_clause)
  (finally_clause)
] @branch

;;!! $foo = 0;
;;!  ^^^
;;!         ^
(_
  (assignment_expression
    left: (_) @name @value.leading.endOf
    right: (_) @value @name.trailing.startOf
  ) @_.domain.start
  .
  ";"? @_.domain.end
)

;;!! $foo += 0;
;;!  ^^^
;;!          ^
(_
  (augmented_assignment_expression
    left: (_) @name @value.leading.endOf
    right: (_) @value @name.trailing.startOf
  ) @_.domain.start
  .
  ";"? @_.domain.end
)

(class_declaration
  name: (_) @name
) @_.domain
(function_definition
  name: (_) @name
) @_.domain
(method_declaration
  name: (_) @name
) @_.domain

;;!! function foo($aaa, $bbb) {}
;;!               ^^^^  ^^^^
(
  (formal_parameters
    (_)? @_.leading.endOf
    .
    (_) @argumentOrParameter
    .
    (_)? @_.trailing.startOf
  ) @_dummy
  (#not-type? @argumentOrParameter "comment")
  (#single-or-multi-line-delimiter! @argumentOrParameter @_dummy ", " ",\n")
)

;;!! foo("bar")
;;!      ^^^^^
(
  (arguments
    (_)? @_.leading.endOf
    .
    (_) @argumentOrParameter
    .
    (_)? @_.trailing.startOf
  ) @_dummy
  (#not-type? @argumentOrParameter "comment")
  (#single-or-multi-line-delimiter! @argumentOrParameter @_dummy ", " ",\n")
)

;;!! function foo($aaa, $bbb) {}
;;!               ^^^^^^^^^^
(_
  (formal_parameters
    "(" @argumentList.removal.start.endOf @argumentOrParameter.iteration.start.endOf
    ")" @argumentList.removal.end.startOf @argumentOrParameter.iteration.end.startOf
  ) @argumentList
  (#empty-single-multi-delimiter! @argumentList @argumentList "" ", " ",\n")
  (#child-range! @argumentList 1 -2)
) @argumentList.domain @argumentOrParameter.iteration.domain

;;!! foo.bar(aaa, bbb);
;;!          ^^^^^^^^
(binary_expression
  (function_call_expression
    (arguments
      "(" @argumentList.removal.start.endOf @argumentOrParameter.iteration.start.endOf
      ")" @argumentList.removal.end.startOf @argumentOrParameter.iteration.end.startOf
    ) @argumentList
    (#empty-single-multi-delimiter! @argumentList @argumentList "" ", " ",\n")
    (#child-range! @argumentList 1 -2)
  )
) @argumentList.domain @argumentOrParameter.iteration.domain

;;!! foo(aaa, bbb);
;;!      ^^^^^^^^
(
  (_
    (arguments
      "(" @argumentList.removal.start.endOf @argumentOrParameter.iteration.start.endOf
      ")" @argumentList.removal.end.startOf @argumentOrParameter.iteration.end.startOf
    ) @argumentList
    (#empty-single-multi-delimiter! @argumentList @argumentList "" ", " ",\n")
    (#child-range! @argumentList 1 -2)
  ) @argumentList.domain @argumentOrParameter.iteration.domain
  (#not-parent-type? @argumentList.domain binary_expression)
)

(arguments
  "(" @name.iteration.start.endOf @value.iteration.start.endOf
  ")" @name.iteration.end.startOf @value.iteration.end.startOf
)

;;!! foo(aaa: 0, bbb: 1);
;;!      ^^^     ^^^
;;!           ^       ^
(argument
  name: (_) @name @value.leading.endOf
  (_) @value @name.trailing.startOf
) @_.domain

;;!! (int $aaa = 0)
;;!   ^^^
;;!       ^^^^
;;!              ^
(simple_parameter
  type: (_)? @type
  name: (_) @name @value.leading.endOf
  default_value: (_)? @value
) @_.domain

;;!! return 0;
;;!         ^
(return_statement
  "return" @_.leading.endOf
  (_) @value
) @_.domain

;;!! yield 0;
;;!        ^
(_
  (yield_expression
    "yield" @_.leading.endOf
    (_) @value
  ) @_.domain.start
  .
  ";"? @_.domain.end
)

;;!! (array ...$nums)
;;!   ^^^^^
;;!            ^^^^^
(variadic_parameter
  type: (_) @type
  name: (_) @name
) @_.domain

;;!! catch (Exception $e) {}
;;!         ^^^^^^^^^^^^
;;!         ^^^^^^^^^
;;!                   ^^
(catch_clause
  type: (_) @type @argumentOrParameter.start @_.domain.start
  name: (_) @name @argumentOrParameter.end @_.domain.end
)

(formal_parameters
  "(" @type.iteration.start.endOf @name.iteration.start.endOf @value.iteration.start.endOf
  ")" @type.iteration.end.startOf @name.iteration.end.startOf @value.iteration.end.startOf
) @_.domain

;;!! (int) $str;
;;!   ^^^
(cast_expression
  type: (_) @type
  value: (_) @_.removal.end.startOf
) @_.removal.start.startOf @_.domain

;;!! public int $foo;
;;!         ^^^
;;!             ^^^^
(property_declaration
  (_)? @name.removal.start.startOf
  type: (_)? @type @name.removal.start.startOf
  (property_element
    name: (_) @name @name.removal.end.endOf @value.leading.endOf
    default_value: (_)? @value @name.removal.end.startOf
  ) @name.removal.start.startOf
) @_.domain @statement

;;!! const int foo = 0;
;;!        ^^^
;;!            ^^^
;;!                  ^
(const_declaration
  type: (_)? @type
  (const_element
    (name) @name @value.leading.endOf
    (_) @value @name.removal.end.startOf
  )
) @name.removal.start.startOf @_.domain

;;!! case foo = 0;
;;!       ^^^
;;!             ^
(enum_case
  "case" @name.removal.start.startOf
  name: (_) @name @value.leading.endOf @name.removal.end.endOf
  value: (_)? @value @name.removal.end.startOf
) @_.domain

(_
  operator: [
    "<"
    "<<"
    "<<="
    "<="
    ">"
    ">="
    ">>"
    ">>="
  ] @disqualifyDelimiter
)
(array_element_initializer
  "=>" @disqualifyDelimiter
)
(heredoc
  "<<<" @disqualifyDelimiter
)
(nowdoc
  "<<<" @disqualifyDelimiter
)
(member_access_expression
  "->" @disqualifyDelimiter
)
(nullsafe_member_access_expression
  "?->" @disqualifyDelimiter
)
(member_call_expression
  "->" @disqualifyDelimiter
)
(nullsafe_member_call_expression
  "?->" @disqualifyDelimiter
)
