;; https://github.com/tree-sitter/tree-sitter-ruby/blob/master/src/grammar.json

;; Generated by the following command:
;; curl https://raw.githubusercontent.com/tree-sitter/tree-sitter-ruby/1ebfdb288842dae5a9233e2509a135949023dd82/src/node-types.json  \
;; | jq '[.[] | select((.type == "_statement" or .type == "_simple_statement") and .type != "_expression") | .subtypes[] | select(.type != "_expression") | .type ]'
[
  (alias)
  (begin_block)
  (end_block)
  (if_modifier)
  (rescue_modifier)
  (undef)
  (unless_modifier)
  (until_modifier)
  (while_modifier)
] @statement

;; Generated by the following command:
;; > curl https://raw.githubusercontent.com/tree-sitter/tree-sitter-ruby/1ebfdb288842dae5a9233e2509a135949023dd82/src/node-types.json \
;; | jq '[.[] | select(.type == _expression or .type == _arg or .type == _primary or .type == _lhs or .type == _simple_numeric or .type == _variable or .type == _nonlocal_variable) | .subtypes[].type | select(startswith(_) | not)] | sort | unique'
(
  (_
    [
      (array)
      (assignment)
      (begin)
      (binary)
      (break)
      (call)
      (case)
      (case_match)
      (chained_string)
      (character)
      (class)
      (class_variable)
      (complex)
      (conditional)
      (constant)
      (delimited_symbol)
      (element_reference)
      (false)
      (float)
      (for)
      (global_variable)
      (hash)
      (heredoc_beginning)
      (identifier)
      (if)
      (instance_variable)
      (integer)
      (lambda)
      (method)
      (module)
      (next)
      (nil)
      (operator_assignment)
      (parenthesized_statements)
      (range)
      (rational)
      (redo)
      (regex)
      (retry)
      (return)
      (scope_resolution)
      (self)
      (simple_symbol)
      (singleton_class)
      (singleton_method)
      (string)
      (string_array)
      (subshell)
      (super)
      (symbol_array)
      (true)
      (unary)
      (unless)
      (until)
      (while)
      (yield)
    ] @statement
  ) @_dummy
  (#type?
    @_dummy
    program
    block_body
    begin_block
    begin
    block
    body_statement
    do_block
    do
    else
    end_block
    ensure
    heredoc_beginning
    interpolation
    lambda
    parenthesized_statements
    singleton_class
    singleton_method
    then
  )
)

(
  (program) @class.iteration @statement.iteration @namedFunction.iteration
  (#document-range! @class.iteration @statement.iteration @namedFunction.iteration)
)

(
  (program) @name.iteration @value.iteration
  (#document-range! @name.iteration @value.iteration)
)

;;!! { }
;;!   ^
(block
  "{" @interior.start.endOf
  "}" @interior.end.startOf
)

(comment) @comment @textFragment

;;!! /foo/
(regex) @regularExpression

;;!! foo()
;;!  ^^^^^
;;!  ^^^
(call
  receiver: (_)? @functionCallee.start
  method: (_) @functionCallee.end
  arguments: (_
    "(" @name.iteration.start.endOf @value.iteration.start.endOf
    ")" @name.iteration.end.startOf @value.iteration.end.startOf
  )
) @functionCall @functionCallee.domain

[
  ;;!! [1, 2, 3]
  (array)
  ;;!! %w[foo bar baz]
  (string_array)
  ;;!! %i[foo bar baz]
  (symbol_array)
] @list

;;!! {aaa: 0, bbb: 1}
(hash) @map

;;!! if true end
;;!     ^^^^
(if
  condition: (_) @condition
) @ifStatement @condition.domain @branch.iteration

;;!! if true end
;;!         ^
(if
  condition: (_) @interior.start.endOf
  consequence: (_)
  .
  _ @interior.end.startOf
)

;;!! if true elsif false end
(if
  "if" @branch.start @branch.removal.start.startOf
  consequence: (_) @branch.end
  (elsif) @branch.removal.end.startOf
  (#character-range! @branch.removal.end.startOf 3)
)

;;!! if true end
;;!! if true else end
(if
  "if" @branch.start @branch.removal.start.startOf
  consequence: (_) @branch.end
  [
    (else) @branch.removal.end.startOf
    "end" @branch.removal.end.endOf
  ]
)

;;!! elsif true end
;;!        ^^^^
(elsif
  "elsif" @branch.start
  condition: (_) @condition
  consequence: (_) @branch.end @condition.domain.end.endOf
) @condition.domain.start.startOf

;;!! elsif true else end
;;!            ^
(elsif
  condition: (_) @interior.start.endOf
  alternative: (_) @interior.end.startOf
)

;;!! elsif true end
;;!            ^
(elsif
  condition: (_) @interior.start.endOf
  !alternative
) @interior.end.endOf

;;!! else end
(else
  "else" @interior.start.endOf
) @branch @interior.end.endOf

;;!! begin rescue end
;;!! begin end
(begin) @branch.iteration

;;!! begin rescue end
(begin
  "begin" @branch.start @branch.removal.start @interior.start.endOf
  (_) @branch.end @branch.removal.end
  .
  (rescue) @interior.end.startOf
)

;;!! begin end
(begin
  "begin" @branch.start @interior.start.endOf
  (_) @branch.end
  .
  "end" @interior.end.startOf
  (#not-type? @branch.end rescue)
) @branch.removal

;;!! rescue end
(begin
  (rescue
    "rescue" @interior.start.endOf
  ) @branch
  "end" @interior.end.startOf
)

;;!! while true end
;;!        ^^^^
(while
  condition: (_) @condition @interior.start.endOf
  (do
    "end" @interior.end.startOf
  )
) @condition.domain

;;!! true ? 0 : 1
;;!  ^^^^
;;!         ^   ^
(conditional
  condition: (_) @condition
  consequence: (_) @branch
) @condition.domain @branch.iteration

(conditional
  alternative: (_) @branch
)

;;!! class Foo end
;;!        ^^^
(class
  name: (_) @name
) @class @_.domain

;;!! class Foo end
;;!           ^
(class
  name: (_) @class.iteration.start.endOf @namedFunction.iteration.start.endOf @statement.iteration.start.endOf
  "end" @class.iteration.end.startOf @namedFunction.iteration.end.startOf @statement.iteration.end.startOf
) @class

(class
  name: (_) @name.iteration.start.endOf @value.iteration.start.endOf @interior.start.endOf
  "end" @name.iteration.end.startOf @value.iteration.end.startOf @interior.end.startOf
) @class

;;!! "Hello world"
(string) @string

[
  (string_content)
  (heredoc_content)
] @textFragment

;;!! def foo() end
;;!      ^^^
(method
  name: (_) @name
  parameters: (_) @interior.start.endOf
  "end" @interior.end.startOf
) @namedFunction @name.domain

;;!! def foo end
;;!      ^^^
(method
  name: (_) @name @interior.start.endOf
  !parameters
  "end" @interior.end.startOf
) @namedFunction @name.domain

;;!! def foo.bar() end
;;!      ^^^
(singleton_method
  name: (_) @name
  parameters: (_) @interior.start.endOf
  "end" @interior.end.startOf
) @namedFunction @name.domain

;;!! def foo.bar end
;;!      ^^^
(singleton_method
  name: (_) @name @interior.start.endOf
  !parameters
  "end" @interior.end.startOf
) @namedFunction @name.domain

;;!! foo = 0
;;!  ^^^
;;!        ^
(assignment
  left: (_) @name @value.leading.endOf
  right: (_) @value @name.trailing.startOf
) @_.domain

;;!! foo += 0
;;!  ^^^
;;!         ^
(operator_assignment
  left: (_) @name @value.leading.endOf
  right: (_) @value @name.trailing.startOf
) @_.domain

;;!! for v in values end
;;!      ^
;;!           ^^^^^^
(for
  pattern: (_) @name
  value: (in
    (_) @value
  ) @interior.start.endOf
  (do
    "end" @interior.end.startOf
  )
) @name.domain @value.domain

;;!! case foo when 0 end
;;!       ^^^
;;!          ^^^^^^^^
(case
  value: (_) @value @condition.iteration.start.endOf @branch.iteration.start.endOf
  "end" @condition.iteration.end.startOf @branch.iteration.end.startOf
) @value.domain

;;!! case foo in 0 end
;;!       ^^^
;;!          ^^^^^^
(case_match
  value: (_) @value @condition.iteration.start.endOf @branch.iteration.start.endOf
  "end" @condition.iteration.end.startOf @branch.iteration.end.startOf
) @value.domain

;;!! when 0
;;!       ^
(when
  pattern: (_) @condition
) @branch @condition.domain

;;!! in foo
;;!     ^^^
(in_clause
  pattern: (_) @condition
) @branch @condition.domain

;;!! %w(foo bar)
;;!     ^^^ ^^^
(
  (string_array
    (bare_string)? @_.leading.endOf
    .
    (bare_string) @collectionItem
    .
    (bare_string)? @_.trailing.startOf
  )
  (#insertion-delimiter! @collectionItem " ")
)

;;!! %i(foo bar)
;;!     ^^^ ^^^
(
  (symbol_array
    (bare_symbol)? @_.leading.endOf
    .
    (bare_symbol) @collectionItem
    .
    (bare_symbol)? @_.trailing.startOf
  )
  (#insertion-delimiter! @collectionItem " ")
)

;;!! -> {}
(lambda) @anonymousFunction

;;!! -> { 0 }
(lambda
  (block
    (block_body
      .
      (_) @value
      .
    )
  )
) @value.domain

;;!! values.each do |v| end
;;!              ^^^^^^^^^^
(do_block) @anonymousFunction

(call
  receiver: (_)? @_dummy_receiver
  method: (_)? @_dummy_method
  block: (_) @anonymousFunction
  (#not-eq? @_dummy_receiver Proc)
  (#not-eq? @_dummy_method lambda)
  (#not-type? @anonymousFunction do_block)
)

;;!! Proc.new { puts "hi" }
;;!  ^^^^^^^^^^^^^^^^^^^^^^
(call
  receiver: (_) @_dummy_receiver
  method: (_) @_dummy_method
  (#eq? @_dummy_receiver Proc)
  (#eq? @_dummy_method new)
) @anonymousFunction

;;!! lambda { puts "hi" }
;;!  ^^^^^^^^^^^^^^^^^^^^
(call
  method: (_) @_dummy
  (#eq? @_dummy lambda)
) @anonymousFunction

;;!! {"1" => "one"}
;;!   ^^^
;;!          ^^^^^
(pair
  key: (_) @collectionKey @value.leading.endOf
  value: (_) @value @collectionKey.trailing.startOf
) @_.domain

;;!! foo(aaa: 0, bbb: 1)
;;!      ^^^
;;!              ^^^
(argument_list
  (pair
    key: (_) @name
    value: (_) @name.trailing.startOf
  ) @name.domain
)

;;!! {"1" => "one", "2" => "two"}
;;!   ^^^^^^^^^^^^^^^^^^^^^^^^^^
(hash
  "{" @collectionKey.iteration.start.endOf @value.iteration.start.endOf
  "}" @collectionKey.iteration.end.startOf @value.iteration.end.startOf
)

;;!! return 0
;;!         ^
(return
  (argument_list) @value
) @value.domain

;;!! def foo(aaa, bbb)
;;!          ^^^  ^^^
(
  (method_parameters
    (_)? @_.leading.endOf
    .
    (_) @argumentOrParameter
    .
    (_)? @_.trailing.startOf
  ) @_dummy
  (#single-or-multi-line-delimiter! @argumentOrParameter @_dummy ", " ",\n")
)

;;!! ->(aaa, bbb) {}
;;!     ^^^  ^^^
(
  (lambda_parameters
    (_)? @_.leading.endOf
    .
    (_) @argumentOrParameter
    .
    (_)? @_.trailing.startOf
  ) @_dummy
  (#single-or-multi-line-delimiter! @argumentOrParameter @_dummy ", " ",\n")
)

;;!! foo(aaa, bbb)
;;!      ^^^  ^^^
(
  (argument_list
    (_)? @_.leading.endOf
    .
    (_) @argumentOrParameter
    .
    (_)? @_.trailing.startOf
  ) @_dummy
  (#single-or-multi-line-delimiter! @argumentOrParameter @_dummy ", " ",\n")
)

;;!! foo{ |aaa, bbb| }
;;!        ^^^  ^^^
(
  (block_parameters
    (_)? @_.leading.endOf
    .
    (_) @argumentOrParameter
    .
    (_)? @_.trailing.startOf
  ) @_dummy
  (#single-or-multi-line-delimiter! @argumentOrParameter @_dummy ", " ",\n")
)

;;!! def foo(aaa, bbb)
;;!          ^^^^^^^^
(_
  (method_parameters
    "(" @argumentList.removal.start.endOf @argumentOrParameter.iteration.start.endOf
    ")" @argumentList.removal.end.startOf @argumentOrParameter.iteration.end.startOf
  ) @argumentList
  (#empty-single-multi-delimiter! @argumentList @argumentList "" ", " ",\n")
  (#child-range! @argumentList 1 -2)
) @argumentList.domain @argumentOrParameter.iteration.domain

(method_parameters
  "(" @name.iteration.start.endOf @value.iteration.start.endOf
  ")" @name.iteration.end.startOf @value.iteration.end.startOf
)

;;!! def foo(aaa, bbb = 0)
;;!          ^^^  ^^^
;;!                     ^
(method_parameters
  [
    (identifier) @name
    (optional_parameter
      name: (_) @name @value.leading.endOf
      value: (_) @value
    ) @_.domain
  ]
)

;;!! ->(aaa, bbb) {}
;;!     ^^^^^^^^
(_
  (lambda_parameters
    "(" @argumentList.removal.start.endOf @argumentOrParameter.iteration.start.endOf
    ")" @argumentList.removal.end.startOf @argumentOrParameter.iteration.end.startOf
  ) @argumentList
  (#empty-single-multi-delimiter! @argumentList @argumentList "" ", " ",\n")
  (#child-range! @argumentList 1 -2)
) @argumentList.domain @argumentOrParameter.iteration.domain

(lambda_parameters
  "(" @name.iteration.start.endOf @value.iteration.start.endOf
  ")" @name.iteration.end.startOf @value.iteration.end.startOf
)

;;!! ->(aaa, bbb = 0)
;;!     ^^^  ^^^
;;!                ^
(lambda_parameters
  [
    (identifier) @name
    (optional_parameter
      name: (_) @name @value.leading.endOf
      value: (_) @value
    ) @_.domain
  ]
)

;;!! foo(aaa, bbb)
;;!      ^^^^^^^^
(_
  (argument_list
    "(" @argumentList.removal.start.endOf @argumentOrParameter.iteration.start.endOf
    ")" @argumentList.removal.end.startOf @argumentOrParameter.iteration.end.startOf
  ) @argumentList
  (#empty-single-multi-delimiter! @argumentList @argumentList "" ", " ",\n")
  (#child-range! @argumentList 1 -2)
) @argumentList.domain @argumentOrParameter.iteration.domain

;;!! foo{ |aaa, bbb| }
;;!        ^^^^^^^^
(call
  (block
    (block_parameters
      "|" @argumentList.removal.start.endOf @argumentOrParameter.iteration.start.endOf
      "|" @argumentList.removal.end.startOf @argumentOrParameter.iteration.end.startOf
    ) @argumentList
    (#empty-single-multi-delimiter! @argumentList @argumentList "" ", " ",\n")
    (#child-range! @argumentList 1 -2)
  )
) @argumentList.domain @argumentOrParameter.iteration.domain

(_
  operator: [
    "<"
    ">"
    "<="
    ">="
    "<<"
    ">>"
    "<<="
    ">>="
  ] @disqualifyDelimiter
)
(pair
  "=>" @disqualifyDelimiter
)
(match_pattern
  "=>" @disqualifyDelimiter
)
