import { Mode } from './settings';

export type ModeConfig = {
  [mode in Mode]: {
    collapseByDefault: boolean;
    defaultCommands: { [section: string]: string[] | undefined };
  };
};

export const ModeConfig: ModeConfig = {
  default: {
    collapseByDefault: false,
    defaultCommands: {
      actions: [
        'cutToClipboard',
        'remove',
        'copyToClipboard',
        'setSelectionAfter',
        'setSelectionBefore',
        'setSelection',
        'pasteFromClipboard',
        'nextHomophone',
        'rename',
        'replaceWithTarget',
        'moveToTarget',
      ],
      scopes: [
        'argumentOrParameter',
        'class',
        'comment',
        'namedFunction',
        'ifStatement',
        'collectionItem',
        'list',
        'map',
        'statement',
        'type',
        'value',
        'line',
        'nonWhitespaceSequence',
        'token',
        'word',
        'character',
      ],
      pairedDelimiters: [
        'whitespace',
        'curlyBrackets',
        'angleBrackets',
        'doubleQuotes',
        'parentheses',
        'backtickQuotes',
        'squareBrackets',
        'singleQuotes',
      ],
    },
  },
  beginner: {
    collapseByDefault: true,
    defaultCommands: {
      actions: [
        'cutToClipboard',
        'remove',
        'copyToClipboard',
        'setSelectionAfter',
        'setSelectionBefore',
        'setSelection',
        'pasteFromClipboard',
        'nextHomophone',
        'rename',
        'replaceWithTarget',
        'moveToTarget',
      ],
      scopes: [
        'argumentOrParameter',
        'class',
        'comment',
        'namedFunction',
        'ifStatement',
        'collectionItem',
        'list',
        'map',
        'statement',
        'type',
        'value',
        'line',
        'nonWhitespaceSequence',
        'token',
        'word',
        'character',
      ],
      pairedDelimiters: [
        'whitespace',
        'curlyBrackets',
        'angleBrackets',
        'doubleQuotes',
        'parentheses',
        'backtickQuotes',
        'squareBrackets',
        'singleQuotes',
      ],
    },
  },
  text: {
    collapseByDefault: true,
    defaultCommands: {
      actions: [
        'scrollToBottom',
        'cutToClipboard',
        'scrollToCenter',
        'remove',
        'clearAndSetSelection',
        'insertCopyBefore',
        'insertCopyAfter',
        'copyToClipboard',
        'scrollToTop',
        'outdentLine',
        'editNewLineBefore',
        'insertEmptyLineBefore',
        'insertEmptyLineAfter',
        'followLink',
        'deselect',
        'highlight',
        'indentLine',
        'setSelectionAfter',
        'editNewLineAfter',
        'setSelectionBefore',
        'insertEmptyLinesAround',
        'findInWorkspace',
        'setSelection',
        'pasteFromClipboard',
        'findInDocument',
        'nextHomophone',
        'rename',
        'replaceWithTarget',
        'moveToTarget',
        'swapTargets',
        'applyFormatter',
      ],
      scopes: [
        'section',
        'paragraph',
        'document',
        'line',
        'nonWhitespaceSequence',
        'boundedNonWhitespaceSequence',
        'url',
        'word',
        'character',
      ],
      pairedDelimiters: [
        'whitespace',
        'curlyBrackets',
        'angleBrackets',
        'doubleQuotes',
        'parentheses',
        'backtickQuotes',
        'squareBrackets',
        'singleQuotes',
      ],
    },
  },
};
