// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const config = {
  user: [{ type: "autogenerated", dirName: "user" }],
  contributing: [{ type: "autogenerated", dirName: "contributing" }],
};

// oxlint-disable-next-line import/no-default-export
export default config;
