// @ts-nocheck

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
export default {
  user: [{ type: "autogenerated", dirName: "user" }],
  contributing: [{ type: "autogenerated", dirName: "contributing" }],
};
