;; import javascript.function.scm
;; import javascript.fieldAccess.scm

;; https://github.com/tree-sitter/tree-sitter-javascript/blob/master/src/grammar.json

;; Statements that are not a child of an export statement
;; Generated by the following command:
;; > curl https://raw.githubusercontent.com/tree-sitter/tree-sitter-typescript/4c20b54771e4b390ee058af2930feb2cd55f2bf8/typescript/src/node-types.json \
;;   | jq '[.[] | select(.type == "statement" or .type == "declaration") | .subtypes[].type]'
(
  [
    (break_statement)
    (class_declaration)
    (continue_statement)
    (debugger_statement)
    (declaration)
    (do_statement)
    (empty_statement)
    (export_statement)
    (for_in_statement)
    (for_statement)
    (generator_function_declaration)
    (import_statement)
    (labeled_statement)
    (return_statement)
    (switch_statement)
    (throw_statement)
    (try_statement)
    (variable_declaration)
    (while_statement)
    (with_statement)
    (class_static_block)

    ;; Disabled on purpose. We have a better definition of this below.
    ;; (if_statement)
    ;; This is disabled since we want the whole statement and not just the block
    ;; (statement_block)
  ] @statement
  (#not-parent-type? @statement export_statement ambient_declaration)
)

(
  [
    (expression_statement)
    (lexical_declaration)
  ] @statement
  (#not-parent-type? @statement export_statement for_statement)
)

(
  (program) @G_statement_name_value_type_class.iteration
  (#document-range! @G_statement_name_value_type_class.iteration)
)

;;!! { }
;;!   ^
(
  (_
    .
    "{" @interior.start.endOf
    "}" @interior.end.startOf
    .
  ) @_dummy
  (#not-type? @_dummy object jsx_expression)
)

;; `name` scope without `export`
(
  (_
    name: (_) @name
  ) @name.domain
  (#not-parent-type? @name.domain export_statement)

  ;; We have special cases for these defined elsewhere
  (#not-type?
    @name.domain
    enum_body
    enum_assignment
    variable_declarator
    method_signature
    method_definition
    abstract_method_signature
    public_field_definition
    field_definition
    generic_type
    property_signature
    type_alias_declaration
  )
)

;; `name` scope with `export`
(export_statement
  (_
    name: (_) @name
  ) @_dummy

  ;; We have a special case for this one.  Note we don't need to list the other
  ;; special cases from above because they can't be exported
  (#not-type? @_dummy variable_declarator type_alias_declaration)
) @name.domain

;; Special cases for `(let | const | var) foo = ...;` because the full statement
;; is actually a grandparent of the `name` node, so we want the domain to include
;; this full grandparent statement.
(
  [
    ;; name:
    ;;!! (const | let) foo = ...;
    ;;!                ^^^
    ;;!  xxxxxxxxxxxxxxxxxxxx
    ;;!  ------------------------
    ;; value:
    ;;!! (const | let) foo = ...;
    ;;!                      ^^^
    ;;!                   xxxxxx
    ;;!  ------------------------
    (lexical_declaration
      .
      [
        (variable_declarator
          name: (_) @name
          value: (_) @name.removal.end.startOf
        )
        (variable_declarator
          name: (_) @name
          !value
        ) @name.removal.end.endOf
      ]
    )

    ;; name:
    ;;!! var foo = ...;
    ;;!      ^^^
    ;;!  xxxxxxxxxx
    ;;!  --------------
    ;; value:
    ;;!! var foo = ...;
    ;;!            ^^^
    ;;!         xxxxxx
    ;;!  --------------
    ;; Note that we can't merge this with the variable declaration above because
    ;; of https://github.com/tree-sitter/tree-sitter/issues/1442#issuecomment-1584628651
    (variable_declaration
      .
      [
        (variable_declarator
          name: (_) @name
          value: (_) @name.removal.end.startOf
        )
        (variable_declarator
          name: (_) @name
          !value
        ) @name.removal.end.endOf
      ]
    )
  ] @name.domain @name.removal.start.startOf
  (#not-parent-type? @name.domain export_statement)

  ;; Handle multiple variable declarators in one statement, eg
  ;;!! (let | const | var) aaa = ..., ccc = ...;
  ;;!  --------------------^^^--------^^^-------
  (#allow-multiple! @name)
)

;; Note that the same domains below will also have the first variable
;; as a target, but that is matched above
(
  [
    ;; name:
    ;;!! (const | let) aaa = 0, bbb = 0;
    ;;!                         ^^^
    ;;!                         xxxxxx
    ;;!  -------------------------------
    ;; value:
    ;;!! (const | let) aaa = 0, bbb = 0;
    ;;!                               ^
    ;;!                            xxxx
    ;;!  -------------------------------
    (lexical_declaration
      (variable_declarator)
      .
      (variable_declarator
        name: (_) @name
        value: (_)? @name.trailing.startOf
      )
    )

    ;; name:
    ;;!! var aaa = 0, bbb = 0;
    ;;!               ^^^
    ;;!               xxxxxx
    ;;!  ---------------------
    ;; value:
    ;;!! var aaa = 0, bbb = 0;
    ;;!                     ^
    ;;!                  xxxx
    ;;!  ---------------------
    ;; Note that we can't merge this with the variable declaration above because
    ;; of https://github.com/tree-sitter/tree-sitter/issues/1442#issuecomment-1584628651
    (variable_declaration
      (variable_declarator)
      .
      (variable_declarator
        name: (_) @name
        value: (_)? @name.trailing.startOf
      )
    )
  ] @name.domain
  (#not-parent-type? @name.domain export_statement)

  ;; Handle multiple variable declarators in one statement, eg
  ;;!! (let | const | var) aaa = ..., ccc = ...;
  ;;!  --------------------^^^--------^^^-------
  (#allow-multiple! @name)
)

(
  (export_statement
    (_
      ;; name:
      ;;!! export (const | let | var) foo = ...;
      ;;!                             ^^^
      ;;!                             xxxxxx
      ;;!  -------------------------------------
      ;; value:
      ;;!! export (const | let | var) foo = 0;
      ;;!                                   ^
      ;;!                                xxxx
      ;;!  -----------------------------------
      (variable_declarator
        name: (_) @name
        value: (_)? @name.trailing.startOf
      )
    )
  ) @name.domain

  ;; Handle multiple variable declarators in one statement, eg
  ;;!! var foo = ..., bar = ...;
  ;;!  ----^^^--------^^^-------
  (#allow-multiple! @name)
)

;; name:
;;!! (const | let | var) aaa = 0, bbb = 0;
;;!                      ^^^
;;!  xxxxxxxxxxxxxxxxxxxxxxxxxx
;;!                      -------
;; value:
;;!! (const | let | var) aaa = 0, bbb = 0;
;;!                            ^
;;!                         xxxx
;;!                      -------
(_
  .
  (variable_declarator
    name: (_) @name @name.removal.end.endOf
    value: (_)? @name.removal.end.startOf
  ) @name.domain
  .
  (variable_declarator)
) @name.removal.start.startOf

;;!! (const | let | var) aaa = 0, bbb = 0;
;;!                               ^^^
;;!                               xxxxxx
;;!                               -------
(_
  (variable_declarator)
  .
  (variable_declarator
    name: (_) @name
    value: (_)? @name.trailing.startOf
  ) @name.domain
)

;; Special cases for `(let | const | var) foo = ...;` because the full statement
;; is actually a grandparent of the `name` node, so we want the domain to include
;; this full grandparent statement.
(
  [
    ;;!! (const | let) aaa: Bbb = 0;
    ;;!                           ^
    ;;!                        xxxx
    ;;!  ---------------------------
    (lexical_declaration
      (variable_declarator
        (_) @value.leading.endOf
        .
        value: (_)? @value
      )
    )

    ;;!! var aaa: Bbb = 0;
    ;;!                 ^
    ;;!              xxxx
    ;;!  -----------------
    ;; Note that we can't merge this with the variable declaration above because
    ;; of https://github.com/tree-sitter/tree-sitter/issues/1442#issuecomment-1584628651
    (variable_declaration
      (variable_declarator
        (_) @value.leading.endOf
        .
        value: (_)? @value
      )
    )
  ] @value.domain
  (#not-parent-type? @value.domain export_statement)

  ;; Handle multiple variable declarators in one statement, eg
  ;;!! (let | const | var) aaa: Bbb = ..., ccc: Ddd = ...;
  ;;!  -------------------------------^^^-------------^^^-
  (#allow-multiple! @value)
)

(
  (export_statement
    (_
      ;;!! export (const | let | var) aaa: Bbb = 0;
      ;;!                                        ^
      ;;!                                     xxxx
      ;;!  ----------------------------------------
      (variable_declarator
        (_) @value.leading.endOf
        .
        value: (_)? @value
      )
    )
  ) @value.domain

  ;; Handle multiple variable declarators in one statement, eg
  ;;!! export (let | const | var) aaa: Bbb = ..., ccc: Ddd = ...;
  ;;!  --------------------------------------^^^-------------^^^-
  (#allow-multiple! @value)
)

;;!! (const | let | var) aaa: Ccc = 0, bbb: Ddd = 0;
;;!1                                ^
;;!1                             xxxx
;;!1                     ------------
;;!2                                              ^
;;!2                                           xxxx
;;!2                                   ------------
(
  (_
    (variable_declarator
      (_) @value.leading.endOf
      .
      value: (_)? @value
    ) @value.domain
  ) @_dummy
  (#has-multiple-children-of-type? @_dummy variable_declarator)
)

;;!! let foo, bar;
;;!      ^^^  ^^^
(
  (lexical_declaration
    (variable_declarator)? @collectionItem.leading.endOf
    .
    (variable_declarator) @collectionItem
    .
    (variable_declarator)? @collectionItem.trailing.startOf
  ) @_dummy
  (#single-or-multi-line-delimiter! @collectionItem @_dummy ", " ",\n")
)

(lexical_declaration
  .
  (_) @collectionItem.iteration.start.startOf
  (_) @collectionItem.iteration.end.endOf
  .
) @collectionItem.iteration.domain

(expression_statement
  [
    ;; name:
    ;;!! foo = 0;
    ;;!  ^^^
    ;;!  xxxxxx
    ;;!  --------
    ;; value:
    ;;!! foo = 0;
    ;;!        ^
    ;;!     xxxx
    ;;!  --------
    (assignment_expression
      left: (_) @name @value.leading.endOf
      right: (_) @value @name.trailing.startOf
    )

    ;; name:
    ;;!! foo += 1;
    ;;!  ^^^
    ;;!  xxxxxxx
    ;;!  ---------
    ;; value:
    ;;!! foo += 1;
    ;;!         ^
    ;;!     xxxxx
    ;;!  ---------
    (augmented_assignment_expression
      left: (_) @name @value.leading.endOf
      right: (_) @value @name.trailing.startOf
    )
  ]
) @_.domain

(
  [
    ;; name:
    ;;!! aaa = 0, bbb = 0;
    ;;!1 ^^^
    ;;!1 xxxxxx
    ;;!1 -------
    ;;!2          ^^^
    ;;!2          xxxxxx
    ;;!2          -------
    ;; value:
    ;;!! aaa = 0, bbb = 0;
    ;;!1       ^
    ;;!1    xxxx
    ;;!1 -------
    ;;!2                ^
    ;;!2             xxxx
    ;;!2          -------
    (assignment_expression
      left: (_) @name @value.leading.endOf
      right: (_) @value @name.trailing.startOf
    )

    ;; name:
    ;;!! aaa += 0, bbb += 0;
    ;;!1 ^^^
    ;;!1 xxxxxxx
    ;;!1 --------
    ;;!2           ^^^
    ;;!2           xxxxxxx
    ;;!2           --------
    ;; value:
    ;;!! aaa += 0, bbb += 0;
    ;;!1        ^
    ;;!1    xxxxx
    ;;!1 --------
    ;;!2                  ^
    ;;!2              xxxxx
    ;;!2           --------
    (augmented_assignment_expression
      left: (_) @name @value.leading.endOf
      right: (_) @value @name.trailing.startOf
    )
  ] @_.domain

  (#not-parent-type? @_.domain expression_statement)
)

;;!! function funk({ value = 2 })
;;!                  ^^^^^
;;!                          ^
(object_assignment_pattern
  left: (_) @collectionKey @value.leading.endOf
  right: (_) @value @collectionKey.trailing.startOf
) @_.domain

;;!! const aaa = {bbb};
;;!               ^^^
(shorthand_property_identifier) @collectionKey @value

;;!! return 0;
;;!         ^
;;!  ---------
(return_statement
  (_) @value
) @value.domain

;;!! yield 0;
;;!        ^
;;!  --------
(_
  (yield_expression
    (_) @value
  ) @value.domain.start
  .
  ";"? @value.domain.end
)

;;!! throw foo;
;;!        ^^^
(throw_statement
  (_) @value
) @value.domain

;;!! str => 0
;;!         ^
;;!  --------
(arrow_function
  body: (_) @value
  (#not-type? @value statement_block)
) @value.domain

;; name:
;;!! for (const aaa of bbb) {}
;;!             ^^^
;;!  ----------------------
;; value:
;;!! for (const aaa of bbb) {}
;;!                    ^^^
;;!  ----------------------
(for_in_statement
  left: (_) @name
  right: (_) @value
) @_.domain

;;!! { }
;;!   ^
(
  (_
    "{" @G_statement_name_value_type.iteration.start.endOf
    "}" @G_statement_name_value_type.iteration.end.startOf
  ) @_dummy
  (#type? @_dummy statement_block class_body interface_body)
)

;;!! const aaa = {bbb: 0, ccc: 0};
;;!               **************
(object
  "{" @G_collectionKey_value.iteration.start.endOf
  "}" @G_collectionKey_value.iteration.end.startOf
)

;;!! const {aaa: bbb} = ccc;
;;!         ^^^^^^^^
(object_pattern
  "{" @G_collectionKey_value.iteration.start.endOf
  "}" @G_collectionKey_value.iteration.end.startOf
)

;;!! const {aaa: bbb} = ccc;
;;!         ^^^
;;!              ^^^
(pair_pattern
  key: (_) @collectionKey @value.leading.endOf
  value: (_) @value @collectionKey.trailing.startOf
) @_.domain

;;!! "string"
;;!! `string`
;;!  ^^^^^^^^
[
  (string)
  (template_string)
] @string

;;  taggedTemplate`hello ${world}`
;;! ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(call_expression
  function: (_) @pairDelimiter.start
  arguments: (template_string
    .
    "`" @pairDelimiter.end
  )
)

;;!! // comment
;;!  ^^^^^^^^^^
(comment) @comment

;;!! /\w+/
;;!  ^^^^^
(regex) @regularExpression

[
  (comment)
  (regex_pattern)
] @textFragment

(
  (string) @textFragment
  (#child-range! @textFragment 0 -1 true true)
)

(
  (template_string) @textFragment
  (#child-range! @textFragment 0 -1 true true)
)

;;!! { value: 0 }
;;!  ^^^^^^^^^^^^
[
  (object)
  (object_pattern)
] @map

;;!! [ 0 ]
;;!  ^^^^^
[
  (array)
  (array_pattern)
] @list

;;!! foo()
;;!  ^^^^^
;;!! new Foo()
;;!  ^^^^^^^^^
[
  (call_expression)
  (new_expression)
] @functionCall

;;!! foo()
;;!  ^^^
;;!  -----
(call_expression
  function: (_) @functionCallee.start
  (_)? @functionCallee.end
  arguments: (_)
) @functionCallee.domain

;;!! new Foo()
;;!  ^^^^^^^
;;!  ---------
(new_expression
  (arguments) @functionCallee.end.startOf
) @functionCallee.start.startOf @functionCallee.domain

;;!! class Foo {}
;;!  ^^^^^^^^^^^^
(
  [
    (class_declaration)
    (class)
  ] @class @type
  (#not-parent-type? @class export_statement)
)

;;!! export class Foo {}
;;!  ^^^^^^^^^^^^^^^^^^^
(export_statement
  [
    (class_declaration)
    (class)
  ]
) @class @type

;;!! true ? 0 : 1
;;!  ^^^^
;;!         ^   ^
(ternary_expression
  condition: (_) @condition
  consequence: (_) @branch
) @condition.domain @branch.iteration

(ternary_expression
  alternative: (_) @branch
)

;;!! for (let i = 0; i < 2; ++i) {}
;;!                  ^^^^^
(for_statement
  condition: (_) @condition
  (#child-range! @condition 0 -1 false true)
) @condition.domain

;;!! while (true) {}
;;!         ^^^^
(while_statement
  condition: (_) @condition
  (#child-range! @condition 0 -1 true true)
) @condition.domain

;;!! do {} while (true);
;;!               ^^^^
(do_statement
  condition: (_) @condition
  (#child-range! @condition 0 -1 true true)
) @condition.domain

;;!! switch (value) { }
;;!          ^^^^^
;;!                  ^
(switch_statement
  value: (_) @value
  body: (_
    "{" @G_branch_condition.iteration.start.endOf
    "}" @G_branch_condition.iteration.end.startOf
  )
  (#child-range! @value 0 -1 true true)
) @value.domain

;;!! case 0: break;
;;!  ^^^^^^^^^^^^^^
;;!       ^
(switch_case
  value: (_) @condition
) @branch @condition.domain

;;!! default: break;
;;!  ^^^^^^^^^^^^^^^
(switch_default) @branch

;;!! case 0: break;
;;!         ^^^^^^^
(switch_case
  ":" @interior.start.endOf
  .
  (_) @_dummy
  (#not-type? @_dummy statement_block)
) @interior.end.endOf

;;!! default: break;
;;!          ^^^^^^^
(switch_default
  ":" @interior.start.endOf
  .
  (_) @_dummy
  (#not-type? @_dummy statement_block)
) @interior.end.endOf

;;!! if () {} else {}
;;!  ^^^^^^^^^^^^^^^^
(
  (if_statement) @ifStatement @statement @branch.iteration
  (#not-parent-type? @ifStatement else_clause)
)

;;!! if () {}
;;!  ^^^^^^^^
(
  (if_statement
    "if" @branch.start.startOf @branch.removal.start.startOf
    condition: (_) @condition
    consequence: (_) @branch.end.endOf @branch.removal.end.endOf
    alternative: (else_clause
      (if_statement)? @branch.removal.end.startOf
    )? @branch.removal.end.startOf
  ) @condition.domain
  (#not-parent-type? @condition.domain else_clause)
  (#child-range! @condition 0 -1 true true)
)

;;!! else if () {}
;;!  ^^^^^^^^^^^^^
(else_clause
  "else" @branch.start.startOf @condition.domain.start.startOf
  (if_statement
    condition: (_) @condition
    consequence: (_) @branch.end.endOf @condition.domain.end.endOf
  )
  (#child-range! @condition 0 -1 true true)
)

;;!! else {}
;;!  ^^^^^^^
(else_clause
  (statement_block)
) @branch

;;!! try () {}
;;!  ^^^^^^^^^
(try_statement
  "try" @branch.start
  body: (_) @branch.end
)

;;!! catch () {}
;;!  ^^^^^^^^^^^
(try_statement
  handler: (_) @branch
)

;;!! finally {}
;;!  ^^^^^^^^^^
(try_statement
  finalizer: (_) @branch
)

;;!! try () {} catch () {} finally {}
;;!  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(try_statement) @branch.iteration

;;!! { value: 0 }
;;!    ^^^^^
;;!    xxxxxxx
;;!! { value: 0 }
;;!           ^
;;!         xxx
;;!    --------
(pair
  key: (_) @collectionKey @value.leading.endOf
  value: (_) @value @collectionKey.trailing.startOf
) @_.domain

;;!! function foo(aaa, bbb) {}
;;!               ^^^  ^^^
(
  (formal_parameters
    (_)? @argumentOrParameter.leading.endOf
    .
    (_) @argumentOrParameter
    .
    (_)? @argumentOrParameter.trailing.startOf
  ) @_dummy
  (#not-type? @argumentOrParameter comment)
  (#single-or-multi-line-delimiter! @argumentOrParameter @_dummy ", " ",\n")
)

;;!! foo(aaa, bbb)
;;!      ^^^  ^^^
(
  (arguments
    (_)? @argumentOrParameter.leading.endOf
    .
    (_) @argumentOrParameter
    .
    (_)? @argumentOrParameter.trailing.startOf
  ) @_dummy
  (#not-type? @argumentOrParameter comment)
  (#single-or-multi-line-delimiter! @argumentOrParameter @_dummy ", " ",\n")
)

(formal_parameters
  "(" @G_name_value_type.iteration.start.endOf
  ")" @G_name_value_type.iteration.end.startOf
)

;;!! foo(aaa, bbb)
;;!      ^^^^^^^^
(_
  (arguments
    "(" @argumentList.removal.start.endOf @argumentOrParameter.iteration.start.endOf
    ")" @argumentList.removal.end.startOf @argumentOrParameter.iteration.end.startOf
  ) @argumentList
  (#empty-single-multi-delimiter! @argumentList @argumentList "" ", " ",\n")
  (#child-range! @argumentList 1 -2)
) @argumentList.domain @argumentOrParameter.iteration.domain

(_
  operator: [
    "<"
    "<<"
    "<<="
    "<="
    ">"
    ">="
    ">>"
    ">>="
    ">>>"
    ">>>="
  ] @disqualifyDelimiter
)

(arrow_function
  "=>" @disqualifyDelimiter
)
