import assert from "node:assert/strict";
import test from "node:test";
import { sidebarItemsGenerator } from "../sidebarItemsGenerator.ts";

type GeneratorArgs = Parameters<typeof sidebarItemsGenerator>[0];

test("groups sidebar items using document and category metadata", async () => {
  const generatedItems = [
    { type: "doc", id: "user/index" },
    { type: "doc", id: "user/install" },
    {
      type: "category",
      label: "Actions",
      collapsible: true,
      collapsed: true,
      customProps: {
        sidebar_group: "Reference",
        sidebar_group_position: 3,
      },
      items: [],
    },
    { type: "doc", id: "user/customization" },
    { type: "doc", id: "user/new-page" },
  ];
  const docs = [
    {
      id: "user/index",
      title: "Cursorless",
      frontMatter: {},
      sidebarPosition: 1,
      source: "",
      sourceDirName: "user",
    },
    {
      id: "user/install",
      title: "Installation",
      frontMatter: {
        sidebar_group: "Getting started",
        sidebar_group_position: 2,
      },
      source: "",
      sourceDirName: "user",
    },
    {
      id: "user/customization",
      title: "Customization",
      frontMatter: {
        sidebar_group: "Customization",
        sidebar_group_position: 4,
      },
      source: "",
      sourceDirName: "user",
    },
    {
      id: "user/new-page",
      title: "New page",
      frontMatter: {},
      source: "",
      sourceDirName: "user",
    },
  ];
  const args = {
    defaultSidebarItemsGenerator: () => generatedItems,
    item: { type: "autogenerated", dirName: "user" },
    docs,
    categoriesMetadata: {},
    numberPrefixParser: () => ({}),
    isCategoryIndex: () => false,
    version: { versionName: "current", contentPath: "" },
  } as unknown as GeneratorArgs;

  const result = await sidebarItemsGenerator(args);

  assert.deepEqual(
    result.map(
      (item) =>
        ("label" in item ? item.label : undefined) ??
        docs.find((doc) => doc.id === ("id" in item ? item.id : undefined))
          ?.title,
    ),
    ["Cursorless", "Getting started", "Reference", "Customization", "New page"],
  );

  const gettingStarted = result[1];
  assert.equal(gettingStarted.type, "category");
  assert.deepEqual(gettingStarted.items, [{ type: "doc", id: "user/install" }]);

  const reference = result[2];
  assert.equal(reference.type, "category");
  assert.deepEqual(reference.items, [generatedItems[2]]);

  const customization = result[3];
  assert.equal(customization.type, "category");
  assert.deepEqual(customization.link, {
    type: "doc",
    id: "user/customization",
  });
  assert.deepEqual(customization.items, []);
});

test("rejects conflicting positions for the same sidebar group", async () => {
  const generatedItems = [
    { type: "doc", id: "user/first" },
    { type: "doc", id: "user/second" },
  ];
  const docs = [
    {
      id: "user/first",
      title: "First",
      frontMatter: {
        sidebar_group: "Reference",
        sidebar_group_position: 1,
      },
      source: "",
      sourceDirName: "user",
    },
    {
      id: "user/second",
      title: "Second",
      frontMatter: {
        sidebar_group: "Reference",
        sidebar_group_position: 2,
      },
      source: "",
      sourceDirName: "user",
    },
  ];
  const args = {
    defaultSidebarItemsGenerator: () => generatedItems,
    item: { type: "autogenerated", dirName: "user" },
    docs,
    categoriesMetadata: {},
    numberPrefixParser: () => ({}),
    isCategoryIndex: () => false,
    version: { versionName: "current", contentPath: "" },
  } as unknown as GeneratorArgs;

  await assert.rejects(
    async () => await sidebarItemsGenerator(args),
    /Conflicting sidebar_group_position values for sidebar group 'Reference': 1 and 2/u,
  );
});
