// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  user: [{ type: "autogenerated", dirName: "user" }],
  contributing: [{ type: "autogenerated", dirName: "contributing" }],
};

module.exports = sidebars;
