/* eslint-disable @typescript-eslint/naming-convention */

import type { LanguageScopeSupportFacetMap } from "./scopeSupportFacets.types";
import { ScopeSupportFacetLevel } from "./scopeSupportFacets.types";

const { supported, notApplicable } = ScopeSupportFacetLevel;

export const shellscriptScopeSupport: LanguageScopeSupportFacetMap = {
  list: supported,

  "argument.actual.singleLine": supported,
  "argument.actual.multiLine": supported,
  "argument.actual.iteration": supported,

  "branch.if": supported,
  "branch.if.elif.else": supported,
  "branch.if.else": supported,
  "branch.if.iteration": supported,
  "branch.switchCase": supported,
  "branch.switchCase.iteration": supported,
  "branch.ternary": supported,
  "branch.ternary.iteration": supported,

  "comment.line": supported,

  "condition.if": supported,
  "condition.while": supported,
  "condition.for": supported,
  "condition.switchCase": supported,
  "condition.switchCase.iteration": supported,
  "condition.ternary": supported,

  functionCall: supported,

  functionCallee: supported,

  namedFunction: supported,
  "namedFunction.iteration.document": supported,

  ifStatement: supported,

  "statement.function": supported,
  "statement.functionCall": supported,
  "statement.if": supported,
  "statement.switch": supported,
  "statement.for": supported,
  "statement.foreach": supported,
  "statement.while": supported,
  "statement.variable.uninitialized": supported,
  "statement.variable.initialized": supported,
  "statement.constant": supported,
  "statement.assignment": supported,
  "statement.assignment.compound": supported,
  "statement.return": supported,
  "statement.break": supported,
  "statement.continue": supported,
  "statement.command": supported,
  "statement.import": supported,
  "statement.misc": supported,
  "statement.update": supported,
  "statement.iteration.document": supported,
  "statement.iteration.block": supported,

  "string.singleLine": supported,
  "string.multiLine": supported,

  "textFragment.comment.line": supported,
  "textFragment.string.singleLine": supported,
  "textFragment.string.multiLine": supported,

  "name.variable.uninitialized": supported,
  "name.variable.initialized": supported,
  "name.constant": supported,
  "name.assignment": supported,
  "name.assignment.compound": supported,
  "name.command": supported,
  "name.foreach": supported,
  "name.function": supported,
  "name.iteration.document": supported,
  "name.iteration.block": supported,

  "value.variable": supported,
  "value.constant": supported,
  "value.assignment": supported,
  "value.assignment.compound": supported,
  "value.mapPair": supported,
  "value.mapPair.iteration": supported,
  "value.foreach": supported,
  "value.return": supported,
  "value.switch": supported,
  "value.iteration.block": supported,
  "value.iteration.document": supported,

  "interior.function": supported,
  "interior.if": supported,
  "interior.switchCase": supported,
  "interior.switch": supported,
  "interior.for": supported,
  "interior.foreach": supported,
  "interior.while": supported,

  "key.mapPair": supported,
  "key.mapPair.iteration": supported,

  command: supported,

  regularExpression: supported,

  disqualifyDelimiter: supported,

  "argumentList.actual.empty": supported,
  "argumentList.actual.singleLine": supported,
  "argumentList.actual.multiLine": supported,

  map: supported,

  /* NOT APPLICABLE */

  // Classes, interfaces, methods, and constructors
  "argument.actual.method.singleLine": notApplicable,
  "argument.actual.method.multiLine": notApplicable,
  "argument.actual.method.iteration": notApplicable,
  "argument.actual.constructor.singleLine": notApplicable,
  "argument.actual.constructor.multiLine": notApplicable,
  "argument.actual.constructor.iteration": notApplicable,
  "argument.formal.method.singleLine": notApplicable,
  "argument.formal.method.multiLine": notApplicable,
  "argument.formal.method.iteration": notApplicable,
  "argument.formal.constructor.singleLine": notApplicable,
  "argument.formal.constructor.multiLine": notApplicable,
  "argument.formal.constructor.iteration": notApplicable,
  "argumentList.actual.method.empty": notApplicable,
  "argumentList.actual.method.singleLine": notApplicable,
  "argumentList.actual.method.multiLine": notApplicable,
  "argumentList.actual.constructor.empty": notApplicable,
  "argumentList.actual.constructor.singleLine": notApplicable,
  "argumentList.actual.constructor.multiLine": notApplicable,
  "argumentList.formal.method.empty": notApplicable,
  "argumentList.formal.method.singleLine": notApplicable,
  "argumentList.formal.method.multiLine": notApplicable,
  "argumentList.formal.constructor.empty": notApplicable,
  "argumentList.formal.constructor.singleLine": notApplicable,
  "argumentList.formal.constructor.multiLine": notApplicable,
  class: notApplicable,
  "class.iteration.document": notApplicable,
  "class.iteration.class": notApplicable,
  "functionCall.constructor": notApplicable,
  "functionCall.method": notApplicable,
  "functionCall.chain": notApplicable,
  "functionCallee.constructor": notApplicable,
  "functionCallee.method": notApplicable,
  "functionCallee.chain": notApplicable,
  "namedFunction.constructor": notApplicable,
  "namedFunction.method": notApplicable,
  "namedFunction.iteration.class": notApplicable,
  "statement.class": notApplicable,
  "statement.interface": notApplicable,
  "statement.field.class": notApplicable,
  "statement.field.interface": notApplicable,
  "statement.constructor": notApplicable,
  "statement.method": notApplicable,
  "statement.method.interface": notApplicable,
  "statement.static": notApplicable,
  "statement.iteration.class": notApplicable,
  "statement.iteration.interface": notApplicable,
  "name.method": notApplicable,
  "name.method.interface": notApplicable,
  "name.constructor": notApplicable,
  "name.class": notApplicable,
  "name.interface": notApplicable,
  "name.field.class": notApplicable,
  "name.field.interface": notApplicable,
  "name.argument.formal.method": notApplicable,
  "name.argument.formal.method.iteration": notApplicable,
  "name.argument.formal.constructor": notApplicable,
  "name.argument.formal.constructor.iteration": notApplicable,
  "name.iteration.class": notApplicable,
  "name.iteration.interface": notApplicable,
  "value.field.class": notApplicable,
  "value.field.interface": notApplicable,
  "value.argument.formal.method": notApplicable,
  "value.argument.formal.method.iteration": notApplicable,
  "value.argument.formal.constructor": notApplicable,
  "value.argument.formal.constructor.iteration": notApplicable,
  "value.iteration.class": notApplicable,
  "type.return.method": notApplicable,
  "type.field.class": notApplicable,
  "type.field.interface": notApplicable,
  "type.class": notApplicable,
  "type.interface": notApplicable,
  "type.argument.formal.method": notApplicable,
  "type.argument.formal.method.iteration": notApplicable,
  "type.argument.formal.constructor": notApplicable,
  "type.argument.formal.constructor.iteration": notApplicable,
  "type.iteration.class": notApplicable,
  "type.iteration.interface": notApplicable,
  "interior.class": notApplicable,
  "interior.interface": notApplicable,
  "interior.constructor": notApplicable,
  "interior.method": notApplicable,
  "interior.static": notApplicable,
  fieldAccess: notApplicable,

  // Enums
  "argument.actual.enum.singleLine": notApplicable,
  "argument.actual.enum.multiLine": notApplicable,
  "argument.actual.enum.iteration": notApplicable,
  "argumentList.actual.enum.empty": notApplicable,
  "argumentList.actual.enum.singleLine": notApplicable,
  "argumentList.actual.enum.multiLine": notApplicable,
  "functionCall.enum": notApplicable,
  "functionCallee.enum": notApplicable,
  "statement.enum": notApplicable,
  "name.enum": notApplicable,
  "name.field.enum": notApplicable,
  "name.iteration.enum": notApplicable,
  "value.field.enum": notApplicable,
  "value.iteration.enum": notApplicable,
  "type.enum": notApplicable,
  "interior.enum": notApplicable,

  // Anonymous functions
  anonymousFunction: notApplicable,
  "argument.formal.lambda.singleLine": notApplicable,
  "argument.formal.lambda.multiLine": notApplicable,
  "argument.formal.lambda.iteration": notApplicable,
  "argumentList.formal.lambda.empty": notApplicable,
  "argumentList.formal.lambda.singleLine": notApplicable,
  "argumentList.formal.lambda.multiLine": notApplicable,
  "name.argument.formal.lambda": notApplicable,
  "name.argument.formal.lambda.iteration": notApplicable,
  "value.return.lambda": notApplicable,
  "value.argument.formal.lambda": notApplicable,
  "value.argument.formal.lambda.iteration": notApplicable,
  "type.return.lambda": notApplicable,
  "type.argument.formal.lambda": notApplicable,
  "type.argument.formal.lambda.iteration": notApplicable,
  "interior.lambda": notApplicable,

  // Exceptions and try / catch
  "argument.formal.catch": notApplicable,
  "branch.try": notApplicable,
  "branch.try.iteration": notApplicable,
  "statement.try": notApplicable,
  "statement.throw": notApplicable,
  "name.argument.catch": notApplicable,
  "value.throw": notApplicable,
  "type.argument.catch": notApplicable,
  "interior.try": notApplicable,

  // Formal parameters and default argument values
  "argument.formal.singleLine": notApplicable,
  "argument.formal.multiLine": notApplicable,
  "argument.formal.iteration": notApplicable,
  "argumentList.formal.empty": notApplicable,
  "argumentList.formal.singleLine": notApplicable,
  "argumentList.formal.multiLine": notApplicable,
  "name.argument.formal": notApplicable,
  "name.argument.formal.iteration": notApplicable,
  "value.argument.formal": notApplicable,
  "value.argument.formal.iteration": notApplicable,
  "type.argument.formal": notApplicable,
  "type.argument.formal.iteration": notApplicable,

  // Keyword arguments
  "name.argument.actual": notApplicable,
  "name.argument.actual.iteration": notApplicable,
  "value.argument.actual": notApplicable,
  "value.argument.actual.iteration": notApplicable,

  // Pattern destructuring
  "statement.variable.destructuring": notApplicable,
  "statement.assignment.destructuring": notApplicable,
  "name.variable.destructuring": notApplicable,
  "name.assignment.destructuring": notApplicable,
  "value.variable.destructuring": notApplicable,
  "value.assignment.destructuring": notApplicable,

  // Type aliases
  "statement.typeAlias": notApplicable,
  "name.typeAlias": notApplicable,
  "value.typeAlias": notApplicable,
  "type.alias": notApplicable,

  // Type annotations and generic types
  "functionCall.generic": notApplicable,
  "functionCallee.generic": notApplicable,
  "type.variable.uninitialized": notApplicable,
  "type.variable.initialized": notApplicable,
  "type.constant": notApplicable,
  "type.return": notApplicable,
  "type.foreach": notApplicable,
  "type.cast": notApplicable,
  "type.typeArgument": notApplicable,
  "type.typeArgument.iteration": notApplicable,
  "type.iteration.block": notApplicable,
  "type.iteration.document": notApplicable,

  // Element and tags
  "textFragment.element": notApplicable,
  "value.attribute": notApplicable,
  "interior.element": notApplicable,
  element: notApplicable,
  tags: notApplicable,
  startTag: notApplicable,
  endTag: notApplicable,
  attribute: notApplicable,
  "key.attribute": notApplicable,

  // Sections and document structure
  section: notApplicable,
  "section.iteration.document": notApplicable,
  "section.iteration.parent": notApplicable,
  chapter: notApplicable,
  subSection: notApplicable,
  subSubSection: notApplicable,
  sectionLevelOne: notApplicable,
  sectionLevelTwo: notApplicable,
  sectionLevelThree: notApplicable,
  sectionLevelFour: notApplicable,
  sectionLevelFive: notApplicable,
  sectionLevelSix: notApplicable,
  namedParagraph: notApplicable,
  subParagraph: notApplicable,
  part: notApplicable,

  // Notebook cells
  "interior.cell": notApplicable,
  notebookCell: notApplicable,

  // Namespaces and package declarations
  "statement.package": notApplicable,
  "statement.namespace": notApplicable,
  "name.namespace": notApplicable,
  "interior.namespace": notApplicable,

  // Resource management blocks
  "statement.resource": notApplicable,
  "name.resource": notApplicable,
  "value.resource": notApplicable,
  "type.resource": notApplicable,
  "interior.resource": notApplicable,

  // Generator yield
  "statement.yield": notApplicable,
  "value.yield": notApplicable,

  // Do-while loops
  "condition.doWhile": notApplicable,
  "statement.doWhile": notApplicable,
  "interior.doWhile": notApplicable,

  // Loop else branches
  "branch.loop": notApplicable,
  "branch.loop.iteration": notApplicable,

  // Block comments
  "comment.block": notApplicable,
  "textFragment.comment.block": notApplicable,

  // Unenclosed comma-separated collections
  "collectionItem.unenclosed.singleLine": notApplicable,
  "collectionItem.unenclosed.multiLine": notApplicable,
  "collectionItem.unenclosed.iteration": notApplicable,

  // Command bodies (as in Talon)
  "value.command": notApplicable,
  "interior.command": notApplicable,

  // Markup environments, selectors, units, and custom delimiter pairs
  pairDelimiter: notApplicable,
  environment: notApplicable,
  selector: notApplicable,
  unit: notApplicable,
};
