name: Forbid TODO

on:
  pull_request:
    types: [opened, synchronize, reopened]
  merge_group:
    branches: [main]

jobs:
  forbid-todo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Forbid TODO
        run: ./scripts/forbid-todo.sh
