import type { LanguageScopeSupportFacetMap } from "./scopeSupportFacets.types";
import { ScopeSupportFacetLevel } from "./scopeSupportFacets.types";

const { supported, unsupported, notApplicable } = ScopeSupportFacetLevel;

export const cCoreScopeSupport: LanguageScopeSupportFacetMap = {
  list: supported,
  ifStatement: supported,
  statement: supported,
  class: supported,
  className: supported,
  namedFunction: supported,

  functionName: supported,
  functionCall: supported,
  functionCallee: supported,
  "argument.actual": supported,
  "argument.actual.iteration": supported,
  "argument.actual.method": supported,
  "argument.actual.method.iteration": supported,
  "argument.formal": supported,
  "argument.formal.iteration": supported,

  "argumentList.actual.empty": unsupported,
  "argumentList.actual.singleLine": unsupported,
  "argumentList.actual.multiLine": unsupported,
  "argumentList.formal.empty": unsupported,
  "argumentList.formal.singleLine": unsupported,
  "argumentList.formal.multiLine": unsupported,

  "comment.line": supported,
  "comment.block": supported,
  "string.singleLine": supported,
  "textFragment.comment.line": supported,
  "textFragment.comment.block": supported,
  "textFragment.string.singleLine": supported,
  disqualifyDelimiter: supported,

  "collectionItem.unenclosed": supported,
  "collectionItem.unenclosed.iteration": supported,

  "name.assignment": supported,
  "name.variable": supported,
  "name.function": supported,
  "name.class": supported,
  "name.field": supported,
  "name.argument.formal": supported,
  "name.argument.formal.iteration": supported,
  "value.assignment": supported,
  "value.variable": supported,
  "value.return": supported,
  "value.return.lambda": supported,
  "value.field": supported,

  "type.variable": supported,
  "type.argument.formal": supported,
  "type.field": supported,
  "type.field.iteration": supported,
  "type.foreach": supported,
  "type.enum": supported,
  "type.cast": supported,
  "type.class": supported,
  "type.return": supported,

  // Unsupported

  switchStatementSubject: unsupported,
  fieldAccess: unsupported,

  "statement.class": unsupported,
  "statement.iteration.document": unsupported,
  "statement.iteration.block": unsupported,

  "class.iteration.document": unsupported,
  "class.iteration.block": unsupported,
  "className.iteration.document": unsupported,
  "className.iteration.block": unsupported,

  "functionName.iteration.document": unsupported,

  "interior.class": unsupported,
  "interior.function": unsupported,
  "interior.if": unsupported,
  "interior.try": unsupported,
  "interior.switchCase": unsupported,
  "interior.ternary": unsupported,
  "interior.loop": unsupported,

  "branch.if": unsupported,
  "branch.if.iteration": unsupported,
  "branch.try": unsupported,
  "branch.try.iteration": unsupported,
  "branch.switchCase": unsupported,
  "branch.switchCase.iteration": unsupported,
  "branch.ternary": unsupported,
  "branch.loop": unsupported,

  "condition.if": unsupported,
  "condition.while": unsupported,
  "condition.doWhile": unsupported,
  "condition.for": unsupported,
  "condition.ternary": unsupported,
  "condition.switchCase": unsupported,
  "condition.switchCase.iteration": unsupported,

  "name.iteration.block": unsupported,
  "name.iteration.document": unsupported,

  "type.argument.formal.iteration": unsupported,

  // Not applicable (C and C++)

  map: notApplicable,
  command: notApplicable,
  notebookCell: notApplicable,
  pairDelimiter: notApplicable,
  "interior.resource": notApplicable,
  "type.resource": notApplicable,
  "type.resource.iteration": notApplicable,
  "name.resource": notApplicable,
  "name.resource.iteration": notApplicable,
  "value.resource": notApplicable,
  "value.resource.iteration": notApplicable,
  element: notApplicable,
  tags: notApplicable,
  startTag: notApplicable,
  endTag: notApplicable,
  section: notApplicable,
  "section.iteration.document": notApplicable,
  "section.iteration.parent": notApplicable,
  environment: notApplicable,
  regularExpression: notApplicable,
  "interior.element": notApplicable,
  "interior.command": notApplicable,
  "interior.cell": notApplicable,
  "string.multiLine": notApplicable,
  "textFragment.string.multiLine": notApplicable,
  "textFragment.element": notApplicable,
  "name.assignment.pattern": notApplicable,
  "name.variable.pattern": notApplicable,
  "value.variable.pattern": notApplicable,
  "name.argument.actual": notApplicable,
  "name.argument.actual.iteration": notApplicable,
  "key.attribute": notApplicable,
  "key.mapPair": notApplicable,
  "key.mapPair.iteration": notApplicable,
  "value.mapPair": notApplicable,
  "value.mapPair.iteration": notApplicable,
  "value.yield": notApplicable,
  "value.attribute": notApplicable,
  "value.argument.actual": notApplicable,
  "value.argument.actual.iteration": notApplicable,
  "type.interface": notApplicable,
  "value.typeAlias": notApplicable,
  "type.alias": notApplicable,
};

export const cScopeSupport: LanguageScopeSupportFacetMap = {
  ...cCoreScopeSupport,

  // These are defined here because we don't want C++  to import them and
  // accidentally forget to add support for them.

  attribute: notApplicable,
  anonymousFunction: notApplicable,
  "interior.lambda": notApplicable,

  "argument.actual.constructor": notApplicable,
  "argument.actual.constructor.iteration": notApplicable,
  "argument.formal.method": notApplicable,
  "argument.formal.method.iteration": notApplicable,
  "argument.formal.constructor": notApplicable,
  "argument.formal.constructor.iteration": notApplicable,
  "argument.formal.lambda": notApplicable,
  "argument.formal.lambda.iteration": notApplicable,

  "argumentList.actual.method.empty": notApplicable,
  "argumentList.actual.method.singleLine": notApplicable,
  "argumentList.actual.method.multiLine": notApplicable,
  "argumentList.actual.constructor.empty": notApplicable,
  "argumentList.actual.constructor.singleLine": notApplicable,
  "argumentList.actual.constructor.multiLine": notApplicable,
  "argumentList.formal.constructor.empty": notApplicable,
  "argumentList.formal.constructor.singleLine": notApplicable,
  "argumentList.formal.constructor.multiLine": notApplicable,
  "argumentList.formal.lambda.empty": notApplicable,
  "argumentList.formal.lambda.singleLine": notApplicable,
  "argumentList.formal.lambda.multiLine": notApplicable,
  "argumentList.formal.method.empty": notApplicable,
  "argumentList.formal.method.singleLine": notApplicable,
  "argumentList.formal.method.multiLine": notApplicable,

  "value.argument.formal": notApplicable,
  "value.argument.formal.iteration": notApplicable,
  "value.argument.formal.method": notApplicable,
  "value.argument.formal.method.iteration": notApplicable,
  "value.argument.formal.constructor": notApplicable,
  "value.argument.formal.constructor.iteration": notApplicable,
  "value.foreach": notApplicable,

  "name.argument.formal.method": notApplicable,
  "name.argument.formal.method.iteration": notApplicable,
  "name.argument.formal.constructor": notApplicable,
  "name.argument.formal.constructor.iteration": notApplicable,
  "name.method": notApplicable,
  "name.constructor": notApplicable,
  "name.foreach": notApplicable,

  "namedFunction.iteration.block": notApplicable,
  "namedFunction.iteration.document": notApplicable,
  "namedFunction.method": notApplicable,
  "namedFunction.method.iteration.class": notApplicable,
  "namedFunction.constructor": notApplicable,

  "functionName.iteration.block": notApplicable,
  "functionName.constructor": notApplicable,
  "functionName.method": notApplicable,
  "functionName.method.iteration.class": notApplicable,

  "functionCall.constructor": notApplicable,
  "functionCallee.constructor": notApplicable,

  "type.argument.formal.method": notApplicable,
  "type.argument.formal.method.iteration": notApplicable,
  "type.argument.formal.constructor": notApplicable,
  "type.argument.formal.constructor.iteration": notApplicable,
  "type.typeArgument": notApplicable,
  "type.typeArgument.iteration": notApplicable,
};
