import type { LanguageScopeSupportFacetMap } from "./scopeSupportFacets.types";
import { ScopeSupportFacetLevel } from "./scopeSupportFacets.types";

const { supported, notApplicable } = ScopeSupportFacetLevel;

export const cssScopeSupport: LanguageScopeSupportFacetMap = {
  "comment.block": supported,
  "string.singleLine": supported,
  disqualifyDelimiter: supported,
  map: supported,

  functionCall: supported,
  functionCallee: supported,

  "argument.actual.singleLine": supported,
  "argument.actual.iteration": supported,

  "argumentList.actual.empty": supported,
  "argumentList.actual.singleLine": supported,
  "argumentList.actual.multiLine": supported,

  "name.iteration.document": supported,
  "name.iteration.block": supported,

  "textFragment.comment.block": supported,
  "textFragment.string.singleLine": supported,

  "key.mapPair": supported,
  "key.mapPair.iteration": supported,

  "value.mapPair": supported,
  "value.mapPair.iteration": supported,

  "collectionItem.unenclosed": supported,
  "collectionItem.unenclosed.iteration": supported,

  statement: supported,
  "statement.iteration.document": supported,

  selector: supported,
  unit: supported,

  /* NOT APPLICABLE */

  // Class
  class: notApplicable,
  "class.iteration.block": notApplicable,
  "class.iteration.document": notApplicable,
  "name.class": notApplicable,
  "name.field.class": notApplicable,
  "name.iteration.class": notApplicable,
  "statement.class": notApplicable,
  "statement.field.class": notApplicable,
  "statement.iteration.class": notApplicable,
  "type.class": notApplicable,
  "type.field.class": notApplicable,
  "type.iteration.class": notApplicable,
  "value.field.class": notApplicable,
  "value.iteration.class": notApplicable,
  "interior.class": notApplicable,
  "namedFunction.iteration.class": notApplicable,

  // Interface
  "statement.interface": notApplicable,
  "statement.field.interface": notApplicable,
  "statement.iteration.interface": notApplicable,
  "name.interface": notApplicable,
  "name.field.interface": notApplicable,
  "name.iteration.interface": notApplicable,
  "type.interface": notApplicable,
  "type.field.interface": notApplicable,
  "type.iteration.interface": notApplicable,
  "interior.interface": notApplicable,

  // Enum
  "statement.enum": notApplicable,
  "name.enum": notApplicable,
  "name.field.enum": notApplicable,
  "name.iteration.enum": notApplicable,
  "value.field.enum": notApplicable,
  "value.iteration.enum": notApplicable,
  "type.enum": notApplicable,
  "interior.enum": notApplicable,

  // Command
  command: notApplicable,
  "name.command": notApplicable,
  "value.command": notApplicable,
  "interior.command": notApplicable,

  // Try catch
  "branch.try": notApplicable,
  "branch.try.iteration": notApplicable,
  "interior.try": notApplicable,
  "argument.catch": notApplicable,
  "name.argument.catch": notApplicable,
  "type.argument.catch": notApplicable,

  anonymousFunction: notApplicable,
  "argument.actual.multiLine": notApplicable,
  "argument.actual.constructor.iteration": notApplicable,
  "argument.actual.constructor.singleLine": notApplicable,
  "argument.actual.constructor.multiLine": notApplicable,
  "argument.actual.method.iteration": notApplicable,
  "argument.actual.method.singleLine": notApplicable,
  "argument.actual.method.multiLine": notApplicable,
  "argument.formal.constructor.iteration": notApplicable,
  "argument.formal.constructor.singleLine": notApplicable,
  "argument.formal.constructor.multiLine": notApplicable,
  "argument.formal.iteration": notApplicable,
  "argument.formal.method.iteration": notApplicable,
  "argument.formal.method.singleLine": notApplicable,
  "argument.formal.method.multiLine": notApplicable,
  "argument.formal.singleLine": notApplicable,
  "argument.formal.multiLine": notApplicable,
  "argument.formal.lambda.singleLine": notApplicable,
  "argument.formal.lambda.multiLine": notApplicable,
  "argument.formal.lambda.iteration": notApplicable,
  "argumentList.actual.method.empty": notApplicable,
  "argumentList.actual.method.singleLine": notApplicable,
  "argumentList.actual.method.multiLine": notApplicable,
  "argumentList.actual.constructor.empty": notApplicable,
  "argumentList.actual.constructor.singleLine": notApplicable,
  "argumentList.actual.constructor.multiLine": notApplicable,
  "argumentList.formal.empty": notApplicable,
  "argumentList.formal.singleLine": notApplicable,
  "argumentList.formal.multiLine": notApplicable,
  "argumentList.formal.lambda.empty": notApplicable,
  "argumentList.formal.lambda.singleLine": notApplicable,
  "argumentList.formal.lambda.multiLine": notApplicable,
  "argumentList.formal.method.empty": notApplicable,
  "argumentList.formal.method.singleLine": notApplicable,
  "argumentList.formal.method.multiLine": notApplicable,
  "argumentList.formal.constructor.empty": notApplicable,
  "argumentList.formal.constructor.singleLine": notApplicable,
  "argumentList.formal.constructor.multiLine": notApplicable,
  attribute: notApplicable,
  "branch.if.iteration": notApplicable,
  "branch.if": notApplicable,
  "branch.if.elif.else": notApplicable,
  "branch.if.else": notApplicable,
  "branch.loop": notApplicable,
  "branch.loop.iteration": notApplicable,
  "branch.switchCase.iteration": notApplicable,
  "branch.switchCase": notApplicable,
  "branch.ternary": notApplicable,
  "branch.ternary.iteration": notApplicable,
  "comment.line": notApplicable,
  "condition.doWhile": notApplicable,
  "condition.for": notApplicable,
  "condition.if": notApplicable,
  "condition.switchCase.iteration": notApplicable,
  "condition.switchCase": notApplicable,
  "condition.ternary": notApplicable,
  "condition.while": notApplicable,
  element: notApplicable,
  endTag: notApplicable,
  environment: notApplicable,
  fieldAccess: notApplicable,
  "functionCall.constructor": notApplicable,
  "functionCallee.constructor": notApplicable,
  ifStatement: notApplicable,
  "interior.cell": notApplicable,
  "interior.element": notApplicable,
  "interior.function": notApplicable,
  "interior.constructor": notApplicable,
  "interior.method": notApplicable,
  "interior.if": notApplicable,
  "interior.lambda": notApplicable,
  "interior.for": notApplicable,
  "interior.foreach": notApplicable,
  "interior.while": notApplicable,
  "interior.doWhile": notApplicable,
  "interior.resource": notApplicable,
  "interior.switch": notApplicable,
  "interior.switchCase": notApplicable,
  "interior.ternary": notApplicable,
  "interior.namespace": notApplicable,
  "interior.static": notApplicable,
  "key.attribute": notApplicable,
  list: notApplicable,
  "name.argument.actual.iteration": notApplicable,
  "name.argument.actual": notApplicable,
  "name.argument.formal.constructor.iteration": notApplicable,
  "name.argument.formal.constructor": notApplicable,
  "name.argument.formal.iteration": notApplicable,
  "name.argument.formal.method.iteration": notApplicable,
  "name.argument.formal.method": notApplicable,
  "name.argument.formal": notApplicable,
  "name.assignment.pattern": notApplicable,
  "name.assignment": notApplicable,
  "name.namespace": notApplicable,
  "name.constructor": notApplicable,
  "name.foreach": notApplicable,
  "name.function": notApplicable,
  "name.method": notApplicable,
  "name.resource.iteration": notApplicable,
  "name.resource": notApplicable,
  "name.variable.pattern": notApplicable,
  "name.variable": notApplicable,
  "namedFunction.constructor": notApplicable,
  "namedFunction.iteration.document": notApplicable,
  "namedFunction.method": notApplicable,
  namedFunction: notApplicable,
  notebookCell: notApplicable,
  pairDelimiter: notApplicable,
  regularExpression: notApplicable,
  "section.iteration.document": notApplicable,
  "section.iteration.parent": notApplicable,
  section: notApplicable,
  startTag: notApplicable,
  "statement.iteration.block": notApplicable,
  "string.multiLine": notApplicable,
  tags: notApplicable,
  "textFragment.comment.line": notApplicable,
  "textFragment.element": notApplicable,
  "textFragment.string.multiLine": notApplicable,
  "type.alias": notApplicable,
  "type.argument.formal.constructor.iteration": notApplicable,
  "type.argument.formal.constructor": notApplicable,
  "type.argument.formal.iteration": notApplicable,
  "type.argument.formal.method.iteration": notApplicable,
  "type.argument.formal.method": notApplicable,
  "type.argument.formal": notApplicable,
  "type.cast": notApplicable,
  "type.foreach": notApplicable,
  "type.resource": notApplicable,
  "type.resource.iteration": notApplicable,
  "type.return": notApplicable,
  "type.typeArgument.iteration": notApplicable,
  "type.typeArgument": notApplicable,
  "type.variable": notApplicable,
  "type.iteration.block": notApplicable,
  "type.iteration.document": notApplicable,
  "value.argument.actual.iteration": notApplicable,
  "value.argument.actual": notApplicable,
  "value.argument.formal.constructor.iteration": notApplicable,
  "value.argument.formal.constructor": notApplicable,
  "value.argument.formal.iteration": notApplicable,
  "value.argument.formal.method.iteration": notApplicable,
  "value.argument.formal.method": notApplicable,
  "value.argument.formal": notApplicable,
  "value.assignment": notApplicable,
  "value.attribute": notApplicable,
  "value.foreach": notApplicable,
  "value.resource.iteration": notApplicable,
  "value.resource": notApplicable,
  "value.return.lambda": notApplicable,
  "value.return": notApplicable,
  "value.typeAlias": notApplicable,
  "value.variable.pattern": notApplicable,
  "value.variable": notApplicable,
  "value.yield": notApplicable,
  "value.switch": notApplicable,
  "value.iteration.block": notApplicable,
  "value.iteration.document": notApplicable,
};
