import type { LanguageScopeSupportFacetMap } from "./scopeSupportFacets.types";
import { ScopeSupportFacetLevel } from "./scopeSupportFacets.types";

const { supported, unsupported, notApplicable } = ScopeSupportFacetLevel;

export const dartScopeSupport: LanguageScopeSupportFacetMap = {
  disqualifyDelimiter: supported,
  list: supported,
  map: supported,
  ifStatement: supported,
  anonymousFunction: supported,

  class: supported,
  "class.iteration.document": supported,

  namedFunction: supported,
  "namedFunction.constructor": supported,
  "namedFunction.method": supported,
  "namedFunction.iteration.document": supported,
  "namedFunction.iteration.class": supported,

  functionCall: supported,
  "functionCall.constructor": supported,
  "functionCall.method": supported,
  "functionCall.chain": supported,
  "functionCall.generic": supported,
  "functionCall.enum": supported,
  "argument.actual.enum": supported,
  "argumentList.actual.enum": supported,
  "argument.actual.enum.iteration": supported,
  functionCallee: supported,
  "functionCallee.constructor": supported,
  "functionCallee.method": supported,
  "functionCallee.chain": supported,
  "functionCallee.generic": supported,
  "functionCallee.enum": supported,

  "argument.actual.singleLine": supported,
  "argument.actual.multiLine": supported,
  "argument.actual.iteration": supported,
  "argument.actual.constructor.singleLine": supported,
  "argument.actual.constructor.multiLine": supported,
  "argument.actual.constructor.iteration": supported,
  "argument.actual.method.singleLine": supported,
  "argument.actual.method.multiLine": supported,
  "argument.actual.method.iteration": supported,
  "argument.formal.singleLine": supported,
  "argument.formal.multiLine": supported,
  "argument.formal.iteration": supported,
  "argument.formal.constructor.singleLine": supported,
  "argument.formal.constructor.multiLine": supported,
  "argument.formal.constructor.iteration": supported,
  "argument.formal.method.singleLine": supported,
  "argument.formal.method.multiLine": supported,
  "argument.formal.method.iteration": supported,
  "argument.formal.lambda.singleLine": supported,
  "argument.formal.lambda.multiLine": supported,
  "argument.formal.lambda.iteration": supported,
  "argument.formal.catch": supported,

  "argumentList.actual.empty": supported,
  "argumentList.actual.singleLine": supported,
  "argumentList.actual.multiLine": supported,
  "argumentList.actual.constructor.empty": supported,
  "argumentList.actual.constructor.singleLine": supported,
  "argumentList.actual.constructor.multiLine": supported,
  "argumentList.actual.method.empty": supported,
  "argumentList.actual.method.singleLine": supported,
  "argumentList.actual.method.multiLine": supported,
  "argumentList.formal.empty": supported,
  "argumentList.formal.singleLine": supported,
  "argumentList.formal.multiLine": supported,
  "argumentList.formal.constructor.empty": supported,
  "argumentList.formal.constructor.singleLine": supported,
  "argumentList.formal.constructor.multiLine": supported,
  "argumentList.formal.method.empty": supported,
  "argumentList.formal.method.singleLine": supported,
  "argumentList.formal.method.multiLine": supported,
  "argumentList.formal.lambda.empty": supported,
  "argumentList.formal.lambda.singleLine": supported,
  "argumentList.formal.lambda.multiLine": supported,

  "collectionItem.unenclosed.singleLine": supported,
  "collectionItem.unenclosed.multiLine": supported,
  "collectionItem.unenclosed.iteration": supported,

  "branch.if": supported,
  "branch.if.elif.else": supported,
  "branch.if.else": supported,
  "branch.if.iteration": supported,
  "branch.try": supported,
  "branch.try.iteration": supported,
  "branch.switchCase": supported,
  "branch.switchCase.iteration": supported,
  "branch.ternary": supported,
  "branch.ternary.iteration": supported,

  "comment.block": supported,
  "comment.line": supported,

  "condition.if": supported,
  "condition.while": supported,
  "condition.doWhile": supported,
  "condition.for": supported,
  "condition.switchCase": supported,
  "condition.switchCase.iteration": supported,
  "condition.ternary": supported,

  "statement.class": supported,
  "statement.enum": supported,
  "statement.field.class": supported,
  "statement.function": supported,
  "statement.constructor": supported,
  "statement.method": supported,
  "statement.functionCall": supported,
  "statement.if": supported,
  "statement.try": supported,
  "statement.switch": supported,
  "statement.for": supported,
  "statement.foreach": supported,
  "statement.while": supported,
  "statement.doWhile": supported,
  "statement.assignment": supported,
  "statement.assignment.compound": supported,
  "statement.constant": supported,
  "statement.variable.uninitialized": supported,
  "statement.variable.initialized": supported,
  "statement.typeAlias": supported,
  "statement.update": supported,
  "statement.return": supported,
  "statement.yield": supported,
  "statement.throw": supported,
  "statement.break": supported,
  "statement.continue": supported,
  "statement.import": supported,
  "statement.iteration.document": supported,
  "statement.iteration.class": supported,
  "statement.iteration.block": supported,

  "string.singleLine": supported,
  "string.multiLine": supported,

  "textFragment.comment.block": supported,
  "textFragment.comment.line": supported,
  "textFragment.string.singleLine": supported,
  "textFragment.string.multiLine": supported,

  "name.argument.actual": supported,
  "name.argument.actual.iteration": supported,
  "name.argument.formal": supported,
  "name.argument.formal.iteration": supported,
  "name.argument.formal.constructor": supported,
  "name.argument.formal.constructor.iteration": supported,
  "name.argument.formal.method": supported,
  "name.argument.formal.method.iteration": supported,
  "name.argument.formal.lambda": supported,
  "name.argument.formal.lambda.iteration": supported,
  "name.argument.catch": supported,
  "name.assignment": supported,
  "name.assignment.compound": supported,
  "name.constant": supported,
  "name.variable.uninitialized": supported,
  "name.variable.initialized": supported,
  "name.foreach": supported,
  "name.function": supported,
  "name.constructor": supported,
  "name.method": supported,
  "name.class": supported,
  "name.enum": supported,
  "name.field.class": supported,
  "name.field.enum": supported,
  "name.typeAlias": supported,
  "name.iteration.document": supported,
  "name.iteration.class": supported,
  "name.iteration.enum": supported,
  "name.iteration.block": supported,

  "key.mapPair": supported,
  "key.mapPair.iteration": supported,

  "value.argument.actual": supported,
  "value.argument.actual.iteration": supported,
  "value.argument.formal": supported,
  "value.argument.formal.iteration": supported,
  "value.argument.formal.lambda": supported,
  "value.argument.formal.lambda.iteration": supported,
  "value.argument.formal.constructor": supported,
  "value.argument.formal.constructor.iteration": supported,
  "value.argument.formal.method": supported,
  "value.argument.formal.method.iteration": supported,
  "value.mapPair": supported,
  "value.mapPair.iteration": supported,
  "value.assignment": supported,
  "value.assignment.compound": supported,
  "value.constant": supported,
  "value.variable": supported,
  "value.foreach": supported,
  "value.return": supported,
  "value.return.lambda": supported,
  "value.switch": supported,
  "value.field.class": supported,
  "value.yield": supported,
  "value.throw": supported,
  "value.typeAlias": supported,
  "value.iteration.document": supported,
  "value.iteration.class": supported,
  "value.iteration.block": supported,

  "type.argument.formal": supported,
  "type.argument.formal.iteration": supported,
  "type.argument.formal.constructor": supported,
  "type.argument.formal.constructor.iteration": supported,
  "type.argument.formal.method": supported,
  "type.argument.formal.method.iteration": supported,
  "type.argument.formal.lambda": supported,
  "type.argument.formal.lambda.iteration": supported,
  "type.argument.catch": supported,
  "type.return": supported,
  "type.return.method": supported,
  "type.foreach": supported,
  "type.field.class": supported,
  "type.constant": supported,
  "type.variable.uninitialized": supported,
  "type.variable.initialized": supported,
  "type.typeArgument": supported,
  "type.typeArgument.iteration": supported,
  "type.class": supported,
  "type.enum": supported,
  "type.alias": supported,
  "type.cast": supported,
  "type.iteration.document": supported,
  "type.iteration.class": supported,
  "type.iteration.block": supported,

  "interior.class": supported,
  "interior.enum": supported,
  "interior.function": supported,
  "interior.constructor": supported,
  "interior.method": supported,
  "interior.lambda": supported,
  "interior.if": supported,
  "interior.try": supported,
  "interior.switch": supported,
  "interior.switchCase": supported,
  "interior.for": supported,
  "interior.foreach": supported,
  "interior.while": supported,
  "interior.doWhile": supported,

  /* UNSUPPORTED  */

  fieldAccess: unsupported,

  /* NOT APPLICABLE */

  // Interface (Dart has abstract classes instead)
  "statement.interface": notApplicable,
  "statement.field.interface": notApplicable,
  "statement.iteration.interface": notApplicable,
  "name.interface": notApplicable,
  "name.field.interface": notApplicable,
  "name.iteration.interface": notApplicable,
  "type.interface": notApplicable,
  "type.field.interface": notApplicable,
  "type.iteration.interface": notApplicable,
  "value.field.interface": notApplicable,
  "interior.interface": notApplicable,

  // Namespace / package declaration statements
  "statement.package": notApplicable,
  "statement.namespace": notApplicable,
  "name.namespace": notApplicable,
  "interior.namespace": notApplicable,

  // Resource statements
  "statement.resource": notApplicable,
  "name.resource": notApplicable,
  "value.resource": notApplicable,
  "type.resource": notApplicable,
  "interior.resource": notApplicable,

  // Command / markup / notebook
  command: notApplicable,
  "statement.command": notApplicable,
  "name.command": notApplicable,
  "value.command": notApplicable,
  "interior.command": notApplicable,
  section: notApplicable,
  "section.iteration.document": notApplicable,
  "section.iteration.parent": notApplicable,
  element: notApplicable,
  tags: notApplicable,
  startTag: notApplicable,
  endTag: notApplicable,
  "interior.element": notApplicable,
  "textFragment.element": notApplicable,
  attribute: notApplicable,
  "key.attribute": notApplicable,
  "value.attribute": notApplicable,
  notebookCell: notApplicable,
  "interior.cell": notApplicable,

  // Language constructs not modeled in Dart this way
  "branch.loop": notApplicable,
  "branch.loop.iteration": notApplicable,
  "statement.assignment.destructuring": notApplicable,
  "statement.variable.destructuring": notApplicable,
  "name.assignment.destructuring": notApplicable,
  "name.variable.destructuring": notApplicable,
  "value.assignment.destructuring": notApplicable,
  "value.variable.destructuring": notApplicable,

  // Enum values
  "value.field.enum": notApplicable,
  "value.iteration.enum": notApplicable,

  // Static statement
  "interior.static": notApplicable,
  "statement.static": notApplicable,

  // Miscellaneous
  "statement.misc": notApplicable,
  "class.iteration.class": notApplicable,
  regularExpression: notApplicable,
  environment: notApplicable,
  selector: notApplicable,
  unit: notApplicable,
  pairDelimiter: notApplicable,
};
