import type { LanguageScopeSupportFacetMap } from "./scopeSupportFacets.types";
import { ScopeSupportFacetLevel } from "./scopeSupportFacets.types";

const { supported, unsupported, notApplicable } = ScopeSupportFacetLevel;

export const javaScopeSupport: LanguageScopeSupportFacetMap = {
  disqualifyDelimiter: supported,
  anonymousFunction: supported,
  list: supported,

  "argument.actual.singleLine": supported,
  "argument.actual.multiLine": supported,
  "argument.actual.iteration": supported,
  "argument.actual.constructor.singleLine": supported,
  "argument.actual.constructor.multiLine": supported,
  "argument.actual.constructor.iteration": supported,
  "argument.actual.method.singleLine": supported,
  "argument.actual.method.multiLine": supported,
  "argument.actual.method.iteration": supported,
  "argument.formal.constructor.singleLine": supported,
  "argument.formal.constructor.multiLine": supported,
  "argument.formal.constructor.iteration": supported,
  "argument.formal.method.singleLine": supported,
  "argument.formal.method.multiLine": supported,
  "argument.formal.method.iteration": supported,
  "argument.formal.lambda.singleLine": supported,
  "argument.formal.lambda.multiLine": supported,
  "argument.formal.lambda.iteration": supported,
  "argument.catch": supported,

  "argumentList.actual.empty": supported,
  "argumentList.actual.singleLine": supported,
  "argumentList.actual.multiLine": supported,
  "argumentList.actual.method.empty": supported,
  "argumentList.actual.method.singleLine": supported,
  "argumentList.actual.method.multiLine": supported,
  "argumentList.actual.constructor.empty": supported,
  "argumentList.actual.constructor.singleLine": supported,
  "argumentList.actual.constructor.multiLine": supported,
  "argumentList.formal.lambda.empty": supported,
  "argumentList.formal.lambda.singleLine": supported,
  "argumentList.formal.lambda.multiLine": supported,
  "argumentList.formal.method.empty": supported,
  "argumentList.formal.method.singleLine": supported,
  "argumentList.formal.method.multiLine": supported,
  "argumentList.formal.constructor.empty": supported,
  "argumentList.formal.constructor.singleLine": supported,
  "argumentList.formal.constructor.multiLine": supported,

  "collectionItem.unenclosed": supported,
  "collectionItem.unenclosed.iteration": supported,

  "branch.if": supported,
  "branch.if.elif.else": supported,
  "branch.if.else": supported,
  "branch.if.iteration": supported,
  "branch.try": supported,
  "branch.try.iteration": supported,
  "branch.switchCase": supported,
  "branch.switchCase.iteration": supported,
  "branch.ternary": supported,
  "branch.ternary.iteration": supported,

  class: supported,
  "class.iteration.block": supported,
  "class.iteration.document": supported,

  "comment.block": supported,
  "comment.line": supported,

  "condition.doWhile": supported,
  "condition.for": supported,
  "condition.if": supported,
  "condition.switchCase": supported,
  "condition.switchCase.iteration": supported,
  "condition.ternary": supported,
  "condition.while": supported,

  functionCall: supported,
  "functionCall.constructor": supported,
  functionCallee: supported,
  "functionCallee.constructor": supported,

  "namedFunction.constructor": supported,
  "namedFunction.method": supported,
  "namedFunction.iteration.class": supported,

  ifStatement: supported,

  "statement.class": supported,
  "statement.interface": supported,
  "statement.enum": supported,
  "statement.field.class": supported,
  "statement.field.interface": supported,
  "statement.constructor": supported,
  "statement.method": supported,
  "statement.if": supported,
  "statement.try": supported,
  "statement.switch": supported,
  "statement.for": supported,
  "statement.foreach": supported,
  "statement.while": supported,
  "statement.doWhile": supported,
  "statement.variable": supported,
  "statement.assignment": supported,
  "statement.return": supported,
  "statement.yield": supported,
  "statement.break": supported,
  "statement.continue": supported,
  "statement.resource": supported,
  "statement.static": supported,
  "statement.iteration.document": supported,
  "statement.iteration.class": supported,
  "statement.iteration.interface": supported,
  "statement.iteration.block": supported,

  "string.singleLine": supported,
  "string.multiLine": supported,

  "textFragment.comment.block": supported,
  "textFragment.comment.line": supported,
  "textFragment.string.singleLine": supported,
  "textFragment.string.multiLine": supported,

  "name.argument.formal.constructor": supported,
  "name.argument.formal.constructor.iteration": supported,
  "name.argument.formal.method": supported,
  "name.argument.formal.method.iteration": supported,
  "name.argument.catch": supported,
  "name.assignment": supported,
  "name.class": supported,
  "name.interface": supported,
  "name.enum": supported,
  "name.constructor": supported,
  "name.field.class": supported,
  "name.field.interface": supported,
  "name.field.enum": supported,
  "name.foreach": supported,
  "name.method": supported,
  "name.variable": supported,
  "name.iteration.document": supported,
  "name.iteration.class": supported,
  "name.iteration.interface": supported,
  "name.iteration.enum": supported,
  "name.iteration.block": supported,
  "name.resource": supported,

  "value.assignment": supported,
  "value.foreach": supported,
  "value.switch": supported,
  "value.field.class": supported,
  "value.return": supported,
  "value.yield": supported,
  "value.return.lambda": supported,
  "value.variable": supported,
  "value.resource": supported,
  "value.iteration.block": supported,
  "value.iteration.class": supported,
  "value.iteration.document": supported,

  "type.argument.formal.constructor": supported,
  "type.argument.formal.method": supported,
  "type.argument.formal.constructor.iteration": supported,
  "type.argument.formal.method.iteration": supported,
  "type.argument.catch": supported,
  "type.foreach": supported,
  "type.field.class": supported,
  "type.field.interface": supported,
  "type.return": supported,
  "type.variable": supported,
  "type.typeArgument": supported,
  "type.typeArgument.iteration": supported,
  "type.resource": supported,
  "type.cast": supported,
  "type.class": supported,
  "type.enum": supported,
  "type.interface": supported,
  "type.iteration.block": supported,
  "type.iteration.class": supported,
  "type.iteration.interface": supported,
  "type.iteration.document": supported,

  "interior.class": supported,
  "interior.interface": supported,
  "interior.enum": supported,
  "interior.constructor": supported,
  "interior.method": supported,
  "interior.if": supported,
  "interior.lambda": supported,
  "interior.for": supported,
  "interior.foreach": supported,
  "interior.while": supported,
  "interior.doWhile": supported,
  "interior.switch": supported,
  "interior.switchCase": supported,
  "interior.ternary": supported,
  "interior.try": supported,
  "interior.resource": supported,
  "interior.static": supported,

  /* UNSUPPORTED  */

  fieldAccess: unsupported,

  /* NOT APPLICABLE */

  // Functions (not methods)
  namedFunction: notApplicable,
  "namedFunction.iteration.document": notApplicable,
  "statement.function": notApplicable,
  "argument.formal.singleLine": notApplicable,
  "argument.formal.multiLine": notApplicable,
  "argument.formal.iteration": notApplicable,
  "argumentList.formal.empty": notApplicable,
  "argumentList.formal.singleLine": notApplicable,
  "argumentList.formal.multiLine": notApplicable,
  "name.argument.formal": notApplicable,
  "name.argument.formal.iteration": notApplicable,
  "name.function": notApplicable,
  "type.argument.formal": notApplicable,
  "type.argument.formal.iteration": notApplicable,
  "interior.function": notApplicable,

  // Element and tags
  element: notApplicable,
  tags: notApplicable,
  startTag: notApplicable,
  endTag: notApplicable,
  "interior.element": notApplicable,
  "textFragment.element": notApplicable,
  attribute: notApplicable,
  "key.attribute": notApplicable,
  "value.attribute": notApplicable,

  // Keyword argument
  "name.argument.actual": notApplicable,
  "name.argument.actual.iteration": notApplicable,
  "value.argument.actual": notApplicable,
  "value.argument.actual.iteration": notApplicable,

  // Pattern destructing
  "name.assignment.pattern": notApplicable,
  "name.variable.pattern": notApplicable,
  "value.variable.pattern": notApplicable,

  // Map literal
  map: notApplicable,
  "key.mapPair": notApplicable,
  "key.mapPair.iteration": notApplicable,
  "value.mapPair": notApplicable,
  "value.mapPair.iteration": notApplicable,

  // Default argument value
  "value.argument.formal": notApplicable,
  "value.argument.formal.iteration": notApplicable,
  "value.argument.formal.constructor": notApplicable,
  "value.argument.formal.constructor.iteration": notApplicable,
  "value.argument.formal.method": notApplicable,
  "value.argument.formal.method.iteration": notApplicable,

  // Type alias
  "type.alias": notApplicable,
  "value.typeAlias": notApplicable,

  // Section
  section: notApplicable,
  "section.iteration.document": notApplicable,
  "section.iteration.parent": notApplicable,

  // Command
  command: notApplicable,
  "statement.command": notApplicable,
  "name.command": notApplicable,
  "value.command": notApplicable,
  "interior.command": notApplicable,

  // Notebook cell
  notebookCell: notApplicable,
  "interior.cell": notApplicable,

  // Multiple resources
  "value.resource.iteration": notApplicable,
  "type.resource.iteration": notApplicable,
  "name.resource.iteration": notApplicable,

  // Namespace
  "statement.namespace": notApplicable,
  "name.namespace": notApplicable,
  "interior.namespace": notApplicable,

  // Branch loop
  "branch.loop": notApplicable,
  "branch.loop.iteration": notApplicable,

  // Values in enum
  "value.field.enum": notApplicable,
  "value.iteration.enum": notApplicable,

  // Miscellaneous
  "statement.misc": notApplicable,
  pairDelimiter: notApplicable,
  regularExpression: notApplicable,
  environment: notApplicable,
  selector: notApplicable,
  unit: notApplicable,
};
