import type { LanguageScopeSupportFacetMap } from "./scopeSupportFacets.types";
import { ScopeSupportFacetLevel } from "./scopeSupportFacets.types";

const { supported, notApplicable } = ScopeSupportFacetLevel;

export const pythonScopeSupport: LanguageScopeSupportFacetMap = {
  "name.foreach": supported,
  "name.resource": supported,
  "name.resource.iteration": supported,
  "name.argument.actual": supported,
  "name.argument.actual.iteration": supported,
  "name.argument.formal": supported,
  "name.argument.formal.constructor": supported,
  "name.argument.formal.constructor.iteration": supported,
  "name.argument.formal.iteration": supported,
  "name.argument.formal.method": supported,
  "name.argument.formal.method.iteration": supported,
  "name.assignment": supported,
  "name.assignment.pattern": supported,
  "name.class": supported,
  "name.constructor": supported,
  "name.field": supported,
  "name.function": supported,
  "name.iteration.block": supported,
  "name.iteration.document": supported,
  "name.method": supported,
  "name.variable": supported,
  "name.variable.pattern": supported,

  "value.foreach": supported,
  "value.yield": supported,
  "value.resource": supported,
  "value.resource.iteration": supported,
  "value.argument.actual": supported,
  "value.argument.actual.iteration": supported,
  "value.argument.formal": supported,
  "value.argument.formal.constructor": supported,
  "value.argument.formal.constructor.iteration": supported,
  "value.argument.formal.iteration": supported,
  "value.argument.formal.method": supported,
  "value.argument.formal.method.iteration": supported,
  "value.assignment": supported,
  "value.field": supported,
  "value.mapPair": supported,
  "value.mapPair.iteration": supported,
  "value.return": supported,
  "value.return.lambda": supported,
  "value.variable": supported,
  "value.variable.pattern": supported,

  "type.argument.formal.constructor": supported,
  "type.argument.formal.constructor.iteration": supported,
  "type.argument.formal.iteration": supported,
  "type.argument.formal.method": supported,
  "type.argument.formal.method.iteration": supported,
  "type.argument.formal": supported,
  "type.class": supported,
  "type.field": supported,
  "type.field.iteration": supported,
  "type.return": supported,
  "type.typeArgument": supported,
  "type.typeArgument.iteration": supported,
  "type.variable": supported,

  anonymousFunction: supported,
  namedFunction: supported,
  "namedFunction.constructor": supported,
  "namedFunction.iteration.document": supported,
  "namedFunction.method": supported,
  "namedFunction.method.iteration.class": supported,

  functionName: supported,
  "functionName.constructor": supported,
  "functionName.iteration.document": supported,
  "functionName.method": supported,
  "functionName.method.iteration.class": supported,

  "argument.actual": supported,
  "argument.actual.iteration": supported,
  "argument.formal": supported,
  "argument.formal.iteration": supported,
  "argument.actual.constructor": supported,
  "argument.actual.constructor.iteration": supported,
  "argument.actual.method": supported,
  "argument.actual.method.iteration": supported,
  "argument.formal.constructor": supported,
  "argument.formal.constructor.iteration": supported,
  "argument.formal.method": supported,
  "argument.formal.method.iteration": supported,
  "argument.formal.lambda": supported,
  "argument.formal.lambda.iteration": supported,

  "argumentList.actual.empty": supported,
  "argumentList.actual.singleLine": supported,
  "argumentList.actual.multiLine": supported,
  "argumentList.actual.method.empty": supported,
  "argumentList.actual.method.singleLine": supported,
  "argumentList.actual.method.multiLine": supported,
  "argumentList.actual.constructor.empty": supported,
  "argumentList.actual.constructor.singleLine": supported,
  "argumentList.actual.constructor.multiLine": supported,
  "argumentList.formal.empty": supported,
  "argumentList.formal.singleLine": supported,
  "argumentList.formal.multiLine": supported,
  "argumentList.formal.lambda.empty": supported,
  "argumentList.formal.lambda.singleLine": supported,
  "argumentList.formal.method.empty": supported,
  "argumentList.formal.method.singleLine": supported,
  "argumentList.formal.method.multiLine": supported,
  "argumentList.formal.constructor.empty": supported,
  "argumentList.formal.constructor.singleLine": supported,
  "argumentList.formal.constructor.multiLine": supported,

  "collectionItem.unenclosed": supported,
  "collectionItem.unenclosed.iteration": supported,

  "branch.if": supported,
  "branch.if.iteration": supported,
  "branch.switchCase": supported,
  "branch.switchCase.iteration": supported,
  "branch.ternary": supported,
  "branch.ternary.iteration": supported,
  "branch.try": supported,
  "branch.try.iteration": supported,
  "branch.loop": supported,
  "branch.loop.iteration": supported,

  class: supported,
  "class.iteration.document": supported,

  className: supported,
  "className.iteration.document": supported,

  "interior.class": supported,
  "interior.function": supported,
  "interior.constructor": supported,
  "interior.method": supported,
  "interior.lambda.expression": supported,
  "interior.if": supported,
  "interior.try": supported,
  "interior.switch": supported,
  "interior.switchCase": supported,
  "interior.ternary": supported,
  "interior.foreach": supported,
  "interior.while": supported,
  "interior.resource": supported,

  switchStatementSubject: supported,

  "condition.if": supported,
  "condition.switchCase": supported,
  "condition.switchCase.iteration": supported,
  "condition.ternary": supported,
  "condition.while": supported,

  "key.mapPair": supported,
  "key.mapPair.iteration": supported,

  list: supported,
  map: supported,

  "comment.line": supported,

  "string.multiLine": supported,
  "string.singleLine": supported,

  "textFragment.comment.line": supported,
  "textFragment.string.multiLine": supported,
  "textFragment.string.singleLine": supported,

  ifStatement: supported,
  statement: supported,
  "statement.class": supported,
  "statement.iteration.block": supported,
  "statement.iteration.document": supported,

  functionCall: supported,
  "functionCall.constructor": supported,
  functionCallee: supported,
  "functionCallee.constructor": supported,

  disqualifyDelimiter: supported,
  pairDelimiter: supported,
  fieldAccess: supported,

  // Not applicable

  "argumentList.formal.lambda.multiLine": notApplicable,
  "class.iteration.block": notApplicable,
  "className.iteration.block": notApplicable,
  "comment.block": notApplicable,
  "condition.doWhile": notApplicable,
  "condition.for": notApplicable,
  "functionName.iteration.block": notApplicable,
  "interior.cell": notApplicable,
  "interior.command": notApplicable,
  "interior.element": notApplicable,
  "interior.lambda.block": notApplicable,
  "interior.for": notApplicable,
  "interior.doWhile": notApplicable,
  "interior.static": notApplicable,
  "interior.namespace": notApplicable,
  "key.attribute": notApplicable,
  "namedFunction.iteration.block": notApplicable,
  "section.iteration.document": notApplicable,
  "section.iteration.parent": notApplicable,
  "textFragment.comment.block": notApplicable,
  "textFragment.element": notApplicable,
  "type.alias": notApplicable,
  "type.cast": notApplicable,
  "type.enum": notApplicable,
  "type.foreach": notApplicable,
  "type.interface": notApplicable,
  "type.resource.iteration": notApplicable,
  "type.resource": notApplicable,
  "value.attribute": notApplicable,
  "value.typeAlias": notApplicable,
  attribute: notApplicable,
  command: notApplicable,
  element: notApplicable,
  endTag: notApplicable,
  environment: notApplicable,
  notebookCell: notApplicable,
  regularExpression: notApplicable,
  section: notApplicable,
  startTag: notApplicable,
  tags: notApplicable,
  selector: notApplicable,
  unit: notApplicable,
};
