import type { LanguageScopeSupportFacetMap } from "./scopeSupportFacets.types";
import { ScopeSupportFacetLevel } from "./scopeSupportFacets.types";

const { supported, unsupported, notApplicable } = ScopeSupportFacetLevel;

export const rScopeSupport: LanguageScopeSupportFacetMap = {
  anonymousFunction: supported,
  "argument.actual": supported,
  "argument.actual.iteration": supported,
  "argument.formal": supported,
  "argument.formal.iteration": supported,

  "argumentList.actual.empty": supported,
  "argumentList.actual.singleLine": supported,
  "argumentList.actual.multiLine": supported,
  "argumentList.actual.method.empty": supported,
  "argumentList.actual.method.singleLine": supported,
  "argumentList.actual.method.multiLine": supported,
  "argumentList.formal.empty": supported,
  "argumentList.formal.singleLine": supported,
  "argumentList.formal.multiLine": supported,
  "argumentList.formal.lambda.empty": supported,
  "argumentList.formal.lambda.singleLine": supported,
  "argumentList.formal.lambda.multiLine": supported,

  "comment.line": supported,
  functionCall: supported,
  functionCallee: supported,
  functionName: supported,
  ifStatement: supported,
  "name.assignment": supported,
  "name.variable": supported,
  namedFunction: supported,
  "value.assignment": supported,
  "value.variable": supported,

  // Unsupported

  "branch.if": unsupported,
  "branch.if.iteration": unsupported,
  "branch.switchCase": unsupported,
  "branch.switchCase.iteration": unsupported,
  "branch.ternary": unsupported,
  "branch.ternary.iteration": unsupported,
  "branch.try": unsupported,
  "branch.try.iteration": unsupported,
  "condition.for": unsupported,
  "condition.if": unsupported,
  "condition.ternary": unsupported,
  "condition.while": unsupported,
  "interior.class": unsupported,
  "interior.function": unsupported,
  "interior.if": unsupported,
  "interior.lambda.block": unsupported,
  "interior.lambda.expression": unsupported,
  "interior.try": unsupported,
  "key.attribute": unsupported,
  "name.class": unsupported,
  "name.field": unsupported,
  "name.foreach": unsupported,
  "name.function": unsupported,
  "name.method": unsupported,
  "statement.class": unsupported,
  "string.multiLine": unsupported,
  "string.singleLine": unsupported,
  "value.attribute": unsupported,
  "value.foreach": unsupported,
  "value.return": unsupported,
  "value.switch": unsupported,
  attribute: unsupported,
  class: unsupported,
  className: unsupported,
  environment: unsupported,
  fieldAccess: unsupported,
  map: unsupported,
  regularExpression: unsupported,

  // Not applicable

  "interior.cell": notApplicable,
  "interior.command": notApplicable,
  "interior.element": notApplicable,
  "name.assignment.pattern": notApplicable,
  "branch.loop": notApplicable,
  "branch.loop.iteration": notApplicable,

  // Not applicable for base language but might be useful for markdown or quarto
  "section.iteration.document": notApplicable,
  "section.iteration.parent": notApplicable,
  "type.alias": notApplicable,
  "type.argument.formal": notApplicable,
  "type.argument.formal.constructor": notApplicable,
  "type.argument.formal.constructor.iteration": notApplicable,
  "type.argument.formal.iteration": notApplicable,
  "type.argument.formal.method": notApplicable,
  "type.argument.formal.method.iteration": notApplicable,
  "type.cast": notApplicable,
  "type.class": notApplicable,
  "type.enum": notApplicable,
  "type.field": notApplicable,
  "type.field.iteration": notApplicable,
  "type.foreach": notApplicable,
  "type.interface": notApplicable,
  "type.resource": notApplicable,
  "type.resource.iteration": notApplicable,
  "type.return": notApplicable,
  "type.typeArgument": notApplicable,
  "type.typeArgument.iteration": notApplicable,
  "type.variable": notApplicable,
  "value.typeAlias": notApplicable,
  "value.variable.pattern": notApplicable,
  command: notApplicable,
  element: notApplicable,
  endTag: notApplicable,
  notebookCell: notApplicable,
  section: notApplicable,
  startTag: notApplicable,
  tags: notApplicable,
};
